<?php
/**
 * Generated by Effect Web Board
 * Wed, 19 Feb 2014 01:34:26 -0300
*/

$installation['is_installed']		= true;
$installation['current_version']	= 0x4E27;
$installation['old_version']		= 0x4E26;
$installation['last_installation']	= 0x51B4512E;
$installation['last_update']		= 0x53043452;