<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_usersonline extends CTM_Command
{
	//============================================
	// Begin: usersonline
	//============================================
	public function usersonline() 
	{
		global $users_online;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "	<div class=\"box-content\">
		<div class=\"header\"><span>{$this->lang->words['UsersOnline']['Title']}</span></div>
        ".(count($users_online['users']) > 0 ? "<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"7\" class=\"tableBackColumn\" style=\"text-align:center;\">
        	<thead>
            	<tr width=\"100%\">
                	<th>{$this->lang->words['UsersOnline']['Table']['Name']}</th>
                    <th>{$this->lang->words['UsersOnline']['Table']['Level']}</th>
                    <th>{$this->lang->words['UsersOnline']['Table']['Resets']}</th>
                    <th>{$this->lang->words['UsersOnline']['Table']['Class']}</th>
                    <th>{$this->lang->words['UsersOnline']['Table']['Map']}</th>
                    ".($users_online['is_room'] == false ? "<th>{$this->lang->words['UsersOnline']['Table']['Room']}</th>" : NULL)."
				</tr>
			</thead>
            <tbody>
            	".$this->loop__usersonline__0x00()."
    		</tbody>
    	</table>" : "".($users_online['is_room'] == true ? "<div class=\"info-box\">{$this->lang->words['UsersOnline']['Messages']['Room']}</div>" : "<div class=\"info-box\">{$this->lang->words['UsersOnline']['Messages']['All']}</div>")."")."
    </div>";
		return $CTM_HTML;
	}
	//============================================
	// End: usersonline
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* usersonline : 0x00 */
	private function loop__usersonline__0x00()
	{
		global $users_online; // PHP Globals
		$content = NULL;

		if(count($users_online['users']) > 0)
		{
			foreach($users_online['users'] as $name => $info)
			{
				$content .= "<tr>
                	<td>{$name}</td>
                    <td>{$info['level']}</td>
                    <td>{$info['resets']}</td>
                    <td>{$info['class']}</td>
                    <td>{$info['map_name']}</td>
                    ".($users_online['is_room'] == false ? "<td>{$info['room']}</td>" : NULL)."
                </tr>
                ";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_usersonline();
$callSkinCache->registry();