<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_notices extends CTM_Command
{
	//============================================
	// Begin: ajax_load_comments
	//============================================
	public function ajax_load_comments() 
	{
		global $ajax_notice_comments;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "	".(count($ajax_notice_comments) > 0 ? "".$this->loop__ajax_load_comments__0x00()."" : NULL)."";
		return $CTM_HTML;
	}
	//============================================
	// End: ajax_load_comments
	//============================================
	//============================================
	// Begin: all_notices
	//============================================
	public function all_notices() 
	{
		global $all_notices;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "	<div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['All_Notices']['Title']}</span></div>
        ".(count($all_notices) > 0 ? "<ul class=\"news\">
        	".$this->loop__all_notices__0x01()."
        </ul>" : "<div class=\"info-box\">{$this->lang->words['All_Notices']['Message']}</div>")."
    </div>";
		return $CTM_HTML;
	}
	//============================================
	// End: all_notices
	//============================================
	//============================================
	// Begin: view_notice
	//============================================
	public function view_notice() 
	{
		global $view_notice, $user_logged_data;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "	<div class=\"box-content\">
    	<div class=\"header\"><span>{$view_notice['title']}</span></div>
        <div class=\"setQuote\">
            <table width=\"100%\" border=\"0\">
                <tr>
                    <td width=\"122\"><img src=\"{$view_notice['author']['image']}\" width=\"120\" height=\"120\" style=\"border: 1px solid #B3B3B3;\" class=\"image\" /></td>
                    <td width=\"1242\">
                        <div class=\"setQuote\">{$this->lang->words['ViewNotice']['Header']}</div>
                        <div class=\"setQuote\" style=\"max-width:563px !important;\">{$view_notice['text']}</div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    ".($view_notice['comments_switch'] == true ? "<div class=\"separator\"><!-- separator line --></div>
    <div class=\"box-content\">
    	<div id=\"noticeComments\"><script>CTM.AjaxLoad(\"?app=core&module=notices&load=loadComments&id={$view_notice['id']}\",'noticeComments');</script></div>
    </div>
    ".(SESSION_USER_LOGGED == true ? "<script type=\"text/javascript\">
	$(function()
	{
		$(\"#commentNotice\").click(function()
		{
			CTM.AjaxLoad(\"?app=core&module=notices&load=commentNotice&id={$view_notice['id']}\",'loadCommentNotice','commentNoticeNow');
		});
	});
	</script>" : NULL)."
    <div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['ViewNotice']['Comment']['Title']}</span></div>
        ".(SESSION_USER_LOGGED == true ? "<form name=\"commentNoticeNow\" id=\"commentNoticeNow\" class=\"frm\">
        	<table width=\"100%\" border=\"0\">
            	<tr>
            		<td class=\"setQuote\">
                		<strong id=\"text\">{$this->lang->words['ViewNotice']['Comment']['Character']}</strong>
                		<select name=\"Character\" id=\"Character\">
                        	".(count($user_logged_data['characters']) > 0 ? "".$this->loop__view_notice__0x02()."" : NULL)."
						</select>
					</td>
                </tr>
                <tr>
                	<td align=\"center\" colspan=\"41\" class=\"setQuote\"><textarea name=\"Text\" id=\"Text\" cols=\"60\" rows=\"7\"></textarea><br />&nbsp;</td>
				</tr>
                <tr>
                	<td align=\"center\" colspan=\"41\"><input type=\"button\" id=\"commentNotice\" value=\"{$this->lang->words['ViewNotice']['Comment']['Button']}\" class=\"btn\" /></td>
            	</tr>
            </table>
		</form>
        <div id=\"loadCommentNotice\"></div>" : "<div class=\"info-box\"> {$this->lang->words['ViewNotice']['Comment']['NotLogged']}</div>")."
	</div>" : NULL)."";
		return $CTM_HTML;
	}
	//============================================
	// End: view_notice
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* ajax_load_comments : 0x00 */
	private function loop__ajax_load_comments__0x00()
	{
		global $ajax_notice_comments; // PHP Globals
		$content = NULL;

		if(count($ajax_notice_comments) > 0)
		{
			foreach($ajax_notice_comments as $comment)
			{
		$header = str_replace(array("$1", "$2"), array($comment['author'], $comment['date']), $this->lang->words['NoticeAjax']['LoadComments']['Header']);
		$content .= "<div class=\"setQuote\">
        <table width=\"100%\" border=\"0\">
        	<tr>
            	<td width=\"122\"><img src=\"{$comment['image']}\" width=\"120\" height=\"120\" style=\"border: 1px solid #B3B3B3;\" class=\"image\" /></td>
                <td width=\"1242\">
                	<div class=\"setQuote\">{$header}</div>
                	<div class=\"setQuote\" style=\"max-width:563px !important;\">{$comment['text']}</div>
    			</td>
    		</tr>
    	</table>
	</div>
	";
			}
		}
		return rtrim($content);
	}
	/* all_notices : 0x01 */
	private function loop__all_notices__0x01()
	{
		global $all_notices; // PHP Globals
		$content = NULL;

		if(count($all_notices) > 0)
		{
			foreach($all_notices as $id => $notice)
			{
				$content .= "<li>&raquo; <a href=\"javascript: void(0);\" onclick=\"CTM.Load('?/notices/view/{$id}','content');\">{$notice['title']}</a> - [ {$notice['date']} ]</li>
            ";
			}
		}
		return rtrim($content);
	}
	/* view_notice : 0x02 */
	private function loop__view_notice__0x02()
	{
		global $user_logged_data; // PHP Globals
		$content = NULL;

		if(count($user_logged_data['characters']) > 0)
		{
			foreach($user_logged_data['characters'] as $character)
			{
				$content .= "<option value=\"{$character}\">{$character}</option>
                        	";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_notices();
$callSkinCache->registry();