<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_downloads extends CTM_Command
{
	//============================================
	// Begin: downloads
	//============================================
	public function downloads() 
	{
		$CTM_HTML = NULL;
		$CTM_HTML .= "	<script type=\"text/javascript\">
	$(function()
	{
		$(\"#DownloadLinks select\").change(function()
		{
			value = $(this).val();
			
			if(value != \"None\")
			{
				linkOriginal = decodeURIComponent(value);
				window.open(linkOriginal, \"Download:\"+Math.random());
				$(this).val(\"None\");
			}
		});
	});
	</script>
	<div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['Downloads']['Title']}</span></div>
        <form name=\"DownloadLinks\" id=\"DownloadLinks\">
        ".$this->loop__downloads__0x02()."
        </form>
        <h4>{$this->lang->words['Downloads']['Requirements']['Title']}</h4>
        <table width=\"100%\" class=\"tableBackColumn\">
        	<tr>
            	<td width=\"118\"><strong>{$this->lang->words['Downloads']['Requirements']['Device']}</strong></td>
                <td width=\"194\"><strong>{$this->lang->words['Downloads']['Requirements']['Minimum']}</strong></td>
                <td width=\"83\"><strong>{$this->lang->words['Downloads']['Requirements']['Recommended']}</strong></td>
            </tr>
            <tr>
            	<td width=\"118\">{$this->lang->words['Downloads']['Requirements']['Processor'][0]}</td>
                <td width=\"118\">{$this->lang->words['Downloads']['Requirements']['Processor'][1]}</td>
                <td width=\"118\">{$this->lang->words['Downloads']['Requirements']['Processor'][2]}</td>
            </tr>
            <tr>
            	<td width=\"194\">{$this->lang->words['Downloads']['Requirements']['Memory'][0]}</td>
                <td width=\"194\">{$this->lang->words['Downloads']['Requirements']['Memory'][1]}</td>
                <td width=\"194\">{$this->lang->words['Downloads']['Requirements']['Memory'][2]}</td>
            </tr>
            <tr>
            	<td width=\"194\">{$this->lang->words['Downloads']['Requirements']['OperationSystem'][0]}</td>
                <td width=\"194\">{$this->lang->words['Downloads']['Requirements']['OperationSystem'][1]}</td>
                <td width=\"194\">{$this->lang->words['Downloads']['Requirements']['OperationSystem'][2]}</td>
            </tr>
            <tr>
            	<td width=\"83\">{$this->lang->words['Downloads']['Requirements']['Graphics'][0]}</td>
                <td width=\"83\">{$this->lang->words['Downloads']['Requirements']['Graphics'][1]}</td>
                <td width=\"83\">{$this->lang->words['Downloads']['Requirements']['Graphics'][2]}</td>
        	</tr>
        </table><br />
        <h4>{$this->lang->words['Downloads']['Drivers']}</h4>
        <div align=\"center\" class=\"setQuote\">
        	<ul id=\"drivers\">
            	<li id=\"ati\"><a target=\"_black\" href=\"http://support.amd.com/us/gpudownload/Pages/index.aspx\"></a></li>
                <li id=\"intel\"><a target=\"_black\" href=\"http://downloadcenter.intel.com/\"></a></li>
                <li id=\"matrox\"><a target=\"_black\" href=\"http://www.matrox.com/mga/support/drivers/\"></a></li>
                <li id=\"nvidia\"><a target=\"_black\" href=\"http://www.nvidia.com/Download/index.aspx\"></a></li>
			</ul>
    	</div>
    </div>";
		return $CTM_HTML;
	}
	//============================================
	// End: downloads
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* downloads : 0x00 */
	private function loop__downloads__0x00($key = NULL, $category = NULL, $file_key = NULL, $FILE = NULL)
	{
		$content = NULL;

		if(count($this->settings['DOWNLOADS']['ARCHIVES'][$key][$file_key]['LINK']) > 0)
		{
			foreach($this->settings['DOWNLOADS']['ARCHIVES'][$key][$file_key]['LINK'] as $i => $l)
			{
		$l = urlencode($l);
		$content .= "<option value=\"{$l}\">{$this->lang->words['Downloads']['Table']['Option']} #{$i}</option>
                        ";
			}
		}
		return rtrim($content);
	}
	/* downloads : 0x01 */
	private function loop__downloads__0x01($key = NULL, $category = NULL)
	{
		$content = NULL;

		if(count($this->settings['DOWNLOADS']['ARCHIVES'][$key]) > 0)
		{
			foreach($this->settings['DOWNLOADS']['ARCHIVES'][$key] as $file_key => $FILE)
			{
				$content .= "<tr>
            	<td>{$FILE['NAME']}</td>
                <td>{$FILE['DESC']}</td>
                <td>{$FILE['SIZE']}</td>
                <td>
                	<select name=\"DownLinks_{$key}_{$file_key}\" id=\"DownLinks_{$key}_{$file_key}\" class=\"selectField\">
                    	<option value=\"None\" selected=\"selected\">{$this->lang->words['Words']['Select']}</option>
                        ".$this->loop__downloads__0x00($key, $category, $file_key, $FILE)."
            		</select>
            	</td>
            </tr>
            ";
			}
		}
		return rtrim($content);
	}
	/* downloads : 0x02 */
	private function loop__downloads__0x02()
	{
		$content = NULL;

		if(count($this->settings['DOWNLOADS']['CATEGORYS']) > 0)
		{
			foreach($this->settings['DOWNLOADS']['CATEGORYS'] as $key => $category)
			{
				$content .= "<h4>{$category}</h4>
        <table width=\"100%\" class=\"tableBackColumn\">
        	<tr>
            	<td width=\"118\"><strong>{$this->lang->words['Downloads']['Table']['Archive']}</strong></td>
                <td width=\"194\"><strong>{$this->lang->words['Downloads']['Table']['Description']}</strong></td>
                <td width=\"83\"><strong>{$this->lang->words['Downloads']['Table']['Size']}</strong></td>
                <td width=\"71\"><strong>{$this->lang->words['Downloads']['Table']['Link']}</strong></td>
            </tr>
            ".$this->loop__downloads__0x01($key, $category)."
		</table><br />
        ";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_downloads();
$callSkinCache->registry();