<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_coinvip extends CTM_Command
{
	//============================================
	// Begin: bankdata
	//============================================
	public function bankdata() 
	{
		$CTM_HTML = NULL;
		$CTM_HTML .= "	<div class=\"box-content\">
		<div class=\"header\"><span>{$this->lang->words['CoinVIP']['BankData']['Title']}</span></div>
		<p> 
			<strong>{$this->lang->words['CoinVIP']['BankData']['Info'][1]}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['BankData']['Info'][2]}<br /><br />
			<strong>{$this->lang->words['CoinVIP']['BankData']['Info'][3]}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['BankData']['Info'][4]}<br /><br />
		</p>
        ".(count($this->settings['PAYMENTMETHOD']['BANK']) > 0 ? "".$this->loop__bankdata__0x02()."" : NULL)."
	</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: bankdata
	//============================================
	//============================================
	// Begin: coinvip
	//============================================
	public function coinvip() 
	{
		global $coinvip;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "	".($coinvip['auto_load_page'] ? "<script type=\"text/javascript\">
	$(document).ready(function(e)
	{
		if(e)
			CTM.AjaxLoad(\"?app=core&module=coinvip&load={$coinvip['auto_load_page']}\", \".showOption\");
    });
    </script>" : NULL)."
    
	<div class=\"box-content\">
		<div class=\"header\"><span>{$this->lang->words['CoinVIP']['Title']}</span></div>
		<ul class=\"info\">
			<li><a href=\"javascript: void(0);\" onclick=\"CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=advantages','.showOption');\">&raquo; {$this->lang->words['CoinVIP']['Menu']['VIP_Advantages']}</a></li>
			<li><a href=\"javascript: void(0);\" onclick=\"CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=howtobuy','.showOption');\">&raquo; {$this->lang->words['CoinVIP']['Menu']['HowToBuy']}</a></li>
			<li><a href=\"javascript: void(0);\" onclick=\"CTM.Load('?app=core&amp;module=userpanel&amp;option=buyVIP','.content');\">&raquo; {$this->lang->words['CoinVIP']['Menu']['BuyVIP']}</a></li>
			<li><a href=\"javascript: void(0);\" onclick=\"CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=bankdata','.showOption');\">&raquo; {$this->lang->words['CoinVIP']['Menu']['BankData']}</a></li>
		</ul>
	</div>
	<div id=\"showOption\"></div>";
		return $CTM_HTML;
	}
	//============================================
	// End: coinvip
	//============================================
	//============================================
	// Begin: howtobuy
	//============================================
	public function howtobuy() 
	{
		$CTM_HTML = NULL;
		$CTM_HTML .= "	<div class=\"box-content\">
		<div class=\"header\"><span>{$this->lang->words['CoinVIP']['HowToBuy']['Title']}</span></div>
		<p>
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['What']}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['What_R']}<br /><br />
            
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Obtain']}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Obtain_R']}<br /><br />
            
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Buy']}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Buy_R']}<br /><br />
            
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Bank'][1]}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Bank'][2]}<br /><br />
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Bank'][3]}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Bank'][4]}<br /><br />
		</p>
		".(count($this->settings['PAYMENTMETHOD']['BANK']) > 0 ? "".$this->loop__howtobuy__0x05()."" : NULL)."
            
		<p>
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Confirm']}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Confirm_R']}<br /><br />
			<strong>{$this->lang->words['CoinVIP']['HowToBuy']['Time']}</strong><br />
			&raquo; {$this->lang->words['CoinVIP']['HowToBuy']['Time_R']}<br /><br />
		</p>
	</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: howtobuy
	//============================================
	//============================================
	// Begin: include_masterResetTable
	//============================================
	public function include_masterResetTable() 
	{
		global $coinvip;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"7\" class=\"tableBackColumn\" style=\"text-align:center;\">
            <thead>
                <tr width=\"100%\">
                    <th>#</th>
                    <th>{$this->lang->words['Words']['Free']}</th>
                    <th>".(VIP_NAME_1)."</th>
                    ".(VIP_NUMBER >= 2 ? "<th>".(VIP_NAME_2)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<th>".(VIP_NAME_3)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<th>".(VIP_NAME_4)."</th>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<th>".(VIP_NAME_5)."</th>" : NULL)."
                </tr>
            </thead>
            <tbody>
            	".($this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] < 3 ? "<tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetsRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_require'][5]}</td>" : NULL)."
                </tr>" : NULL)."
            	<tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['LevelReset']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['level_reset'][5]}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['StrengthRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['DexterityRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['VitalityRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['EnergyRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>" : NULL)."
                </tr>
                ".(MUSERVER_VERSION >= 1 ? "<tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['CommandRequire']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['command_require']}</td>" : NULL)."
                </tr>" : NULL)."
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['MoneyReset']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['money_require'][5]}</td>" : NULL)."
                </tr>
                ".($this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] == 1 ? "<tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetsRemove']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['resets_remove'][5]}</td>" : NULL)."
                </tr>" : NULL)."
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetPoints']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['reset_points'][5]}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearInvent']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_invent'][5]}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearSkill']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_skill'][5]}</td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearQuest']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['clear_quest'][5]}</td>" : NULL)."
                </tr>
                <tr>
                    <td style=\"color:#FF0000\">{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['CoinAward']}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][0]}</td>
                    <td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['masterResetTable']['coin_award'][5]}</td>" : NULL)."
                </tr>
            </tbody>
        </table>";
		return $CTM_HTML;
	}
	//============================================
	// End: include_masterResetTable
	//============================================
	//============================================
	// Begin: include_resetTable
	//============================================
	public function include_resetTable() 
	{
		global $coinvip;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "".($this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] < 4 ? "<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"7\" class=\"tableBackColumn\" style=\"text-align:center;\">
        	<thead>
            	<tr width=\"100%\">
                	<th>#</th>
                    <th>{$this->lang->words['Words']['Free']}</th>
                    <th>".(VIP_NAME_1)."</th>
                    ".(VIP_NUMBER >= 2 ? "<th>".(VIP_NAME_2)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<th>".(VIP_NAME_3)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<th>".(VIP_NAME_4)."</th>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<th>".(VIP_NAME_5)."</th>" : NULL)."
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelReset']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['level_reset'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['level_reset'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_reset'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_reset'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_reset'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_reset'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['MoneyReset']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['money_require'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['money_require'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['money_require'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['money_require'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['money_require'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['money_require'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelAfter']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['level_after'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['level_after'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_after'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_after'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_after'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['level_after'][5]}</td>" : NULL)."
                </tr>
                ".($this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0 ? "<tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['SetPoints']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['set_points'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['set_points'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['set_points'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['set_points'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['set_points'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['set_points'][5]}</td>" : NULL)."
                </tr>" : NULL)."
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearInvent']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_invent'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearSkill']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_skill'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearQuest']}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][0]}</td>
                    <td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$coinvip['vip_advantages']['resetTable']['clear_quest'][5]}</td>" : NULL)."
                </tr>
			</tbody>
		</table>" : "".$this->loop__include_resetTable__0x06()."")."";
		return $CTM_HTML;
	}
	//============================================
	// End: include_resetTable
	//============================================
	//============================================
	// Begin: vip_advantages
	//============================================
	public function vip_advantages() 
	{
		global $coinvip;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "    <div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['CoinVIP']['VIP_Advantages']['Title']}</span></div>
    	<p>
        	{$this->lang->words['CoinVIP']['VIP_Advantages']['Text']}
		</p>
    </div>
    <div class=\"box-content\">
        <div class=\"header\"><span>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Title']}</span></div>
        <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"7\" class=\"tableBackColumn\" style=\"text-align:center;\">
            <thead>
                <tr width=\"100%\">
                    <th>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Service']}</th>
                    <th>{$this->lang->words['Words']['Free']}</th>
                    <th>".(VIP_NAME_1)."</th>
                    ".(VIP_NUMBER >= 2 ? "<th>".(VIP_NAME_2)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<th>".(VIP_NAME_3)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<th>".(VIP_NAME_4)."</th>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<th>".(VIP_NAME_5)."</th>" : NULL)."
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeData']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_DATA'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeMail']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangePID']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_PID'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['VirtualVault']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['DisconnectGame']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ResetSystem']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['MasterReset']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MASTER_RESET'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['TransferResets']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ClearPk']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CLEAR_PK'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeClass']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeName']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_NAME'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['MoveCharacter']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ManageProfile']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeAvatar']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['RepairPoints']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['RedistributePoints']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
                <tr>
                    <td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['DistributePoints']}</td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][0]}.png\" style=\"border: none;\" /></td>
                    <td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][1]}.png\" style=\"border: none;\" /></td>
                    ".(VIP_NUMBER >= 2 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][2]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][3]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][4]}.png\" style=\"border: none;\" /></td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td><img src=\"{$this->vars['style_dirs']['images']}icons/{$coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][5]}.png\" style=\"border: none;\" /></td>" : NULL)."
                </tr>
            </tbody>
        </table>
    </div>
    <div class=\"box-content\">
        <div class=\"header\"><span>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['Title']}</span></div>
        ".$this->include_resetTable()."
    </div>
    <div class=\"box-content\">
        <div class=\"header\"><span>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['Title']}</span></div>
        ".$this->include_masterResetTable()."
    </div>";
		return $CTM_HTML;
	}
	//============================================
	// End: vip_advantages
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* bankdata : 0x00 */
	private function loop__bankdata__0x00($_key = NULL, $trash = NULL, $k = NULL, $_trash = NULL)
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK'][$_key][$k]) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'][$_key][$k] as $key => $value)
			{
				$content .= "&raquo; <strong>{$key}</strong> {$value}<br />
            ";
			}
		}
		return rtrim($content);
	}
	/* bankdata : 0x01 */
	private function loop__bankdata__0x01($_key = NULL, $trash = NULL)
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK'][$_key]) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'][$_key] as $k => $_trash)
			{
				$content .= "".$this->loop__bankdata__0x00($_key, $trash, $k, $_trash)."
			";
			}
		}
		return rtrim($content);
	}
	/* bankdata : 0x02 */
	private function loop__bankdata__0x02()
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK']) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'] as $_key => $trash)
			{
				$content .= "<div class=\"blockquote\">
			".$this->loop__bankdata__0x01($_key, $trash)."
		</div>
		";
			}
		}
		return rtrim($content);
	}
	/* howtobuy : 0x03 */
	private function loop__howtobuy__0x03($_key = NULL, $trash = NULL, $k = NULL, $_trash = NULL)
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK'][$_key][$k]) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'][$_key][$k] as $key => $value)
			{
				$content .= "&raquo; <strong>{$key}</strong> {$value}<br />
            ";
			}
		}
		return rtrim($content);
	}
	/* howtobuy : 0x04 */
	private function loop__howtobuy__0x04($_key = NULL, $trash = NULL)
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK'][$_key]) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'][$_key] as $k => $_trash)
			{
				$content .= "".$this->loop__howtobuy__0x03($_key, $trash, $k, $_trash)."
			";
			}
		}
		return rtrim($content);
	}
	/* howtobuy : 0x05 */
	private function loop__howtobuy__0x05()
	{
		$content = NULL;

		if(count($this->settings['PAYMENTMETHOD']['BANK']) > 0)
		{
			foreach($this->settings['PAYMENTMETHOD']['BANK'] as $_key => $trash)
			{
				$content .= "<div class=\"blockquote\">
			".$this->loop__howtobuy__0x04($_key, $trash)."
		</div>
		";
			}
		}
		return rtrim($content);
	}
	/* include_resetTable : 0x06 */
	private function loop__include_resetTable__0x06()
	{
		global $coinvip; // PHP Globals
		$content = NULL;

		if(count($coinvip['vip_advantages']['resetTable']) > 0)
		{
			foreach($coinvip['vip_advantages']['resetTable'] as $key => $table)
			{
				$content .= "<h4>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['Table']} {$key}</h4>
        <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"7\" class=\"tableBackColumn\" style=\"text-align:center;\">
        	<thead>
            	<tr width=\"100%\">
                	<th>#</th>
                    <th>{$this->lang->words['Words']['Free']}</th>
                    <th>".(VIP_NAME_1)."</th>
                    ".(VIP_NUMBER >= 2 ? "<th>".(VIP_NAME_2)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<th>".(VIP_NAME_3)."</th>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<th>".(VIP_NAME_4)."</th>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<th>".(VIP_NAME_5)."</th>" : NULL)."
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelReset']}</td>
                    <td>{$table['level_reset'][0]}</td>
                    <td>{$table['level_reset'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['level_reset'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['level_reset'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['level_reset'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['level_reset'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['MoneyReset']}</td>
                    <td>{$table['money_require'][0]}</td>
                    <td>{$table['money_require'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['money_require'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['money_require'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['money_require'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['money_require'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelAfter']}</td>
                    <td>{$table['level_after'][0]}</td>
                    <td>{$table['level_after'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['level_after'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['level_after'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['level_after'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['level_after'][5]}</td>" : NULL)."
                </tr>
                ".($this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0 ? "<tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['SetPoints']}</td>
                    <td>{$table['set_points'][0]}</td>
                    <td>{$table['set_points'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['set_points'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['set_points'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['set_points'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['set_points'][5]}</td>" : NULL)."
                </tr>" : NULL)."
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearInvent']}</td>
                    <td>{$table['clear_invent'][0]}</td>
                    <td>{$table['clear_invent'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['clear_invent'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['clear_invent'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['clear_invent'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['clear_invent'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearSkill']}</td>
                    <td>{$table['clear_skill'][0]}</td>
                    <td>{$table['clear_skill'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['clear_skill'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['clear_skill'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['clear_skill'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['clear_skill'][5]}</td>" : NULL)."
                </tr>
                <tr>
                	<td>{$this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearQuest']}</td>
                    <td>{$table['clear_quest'][0]}</td>
                    <td>{$table['clear_quest'][1]}</td>
                    ".(VIP_NUMBER >= 2 ? "<td>{$table['clear_quest'][2]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 3 ? "<td>{$table['clear_quest'][3]}</td>" : NULL)."
                    ".(VIP_NUMBER >= 4 ? "<td>{$table['clear_quest'][4]}</td>" : NULL)."
                    ".(VIP_NUMBER == 5 ? "<td>{$table['clear_quest'][5]}</td>" : NULL)."
                </tr>
			</tbody>
		</table>
        ";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_coinvip();
$callSkinCache->registry();