<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_home extends CTM_Command
{
	//============================================
	// Begin: homePage
	//============================================
	public function homePage() 
	{
		global $home_module;  // PHP Globals

		/* Start PHP Codes */
		$this->tmp_vars['target'] = $this->settings['HOME']['FORUM']['NEW_WINDOW'] == true ? " target=\"_blank\"" : NULL;
		/* End PHP Codes */

		$CTM_HTML = NULL;
		$CTM_HTML .= "	".($home_module['rankingData'] != 'NONE_RANK' ? "<script type=\"text/javascript\">
	$(function()
	{
		$(\"td[rel*=SelectRanking]\").click(function()
		{
			rank = $(this).attr(\"id\");
	
			$(\".currentRanking\").hide().ready(function()
			{
				$(\"#Ranking_\"+rank).show(\"slow\"); 
				$(\"td[rel*=SelectRanking]\").attr(\"class\", \"\");
				$(\"#\"+rank).attr(\"class\", \"current\");
			});
		});
		$(\".currentRanking\").hide().ready(function()
		{
			$(\"#Ranking_{$home_module['rankingData']}\").show(\"slow\"); 
			$(\"#{$home_module['rankingData']}\").attr(\"class\", \"current\");
		});
		$(\".rankLink\").click(function()
		{
			var charName = encodeURIComponent($(this).attr(\"rel\"));
			CTM.Load(\"?/char/\"+charName, \"content\");
		});
		$(\".guildLink\").click(function()
		{
			var guildName = encodeURIComponent($(this).attr(\"rel\"));
			CTM.Load(\"?/guild/\"+guildName, \"content\");
		});
	});
	</script>" : NULL)."
    ".($this->settings['HOME']['NOTICES']['SHOW'] == true ? "<div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['Home']['Notices']['Title']}</span></div>
        ".(count($home_module['webNotices']) > 0 ? "<ul class=\"news\">
        	".$this->loop__homePage__0x00()."
        </ul>
        <div class=\"right\"><a href=\"javascript: void(0);\" onclick=\"CTM.Load('?/notices','content');\">[ {$this->lang->words['Home']['Notices']['All']} ]</a></div>" : "<div class=\"info-box\">{$this->lang->words['Home']['Notices']['Void']}</div>")."
    </div>" : NULL)."
    
    ".($this->settings['HOME']['FORUM']['SHOW'] == true ? "<div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['Home']['ForumNotices']['Title']}</span></div>
        ".($home_module['forumNotices'] ? "".(count($home_module['forumNotices']) > 0 ? "		<ul class=\"news\">
        	".$this->loop__homePage__0x01()."
        </ul>" : "<div class=\"info-box\">{$this->lang->words['Home']['ForumNotices']['Void']}</div>")."" : "<div class=\"error-box\">{$this->lang->words['Home']['ForumNotices']['Error']}</div>")."
    </div>" : NULL)."
    
    ".($this->settings['HOME']['SIEGE']['SHOW'] == true ? "<div class=\"box-content\">
    	<div id=\"castle-siege\">
        	<p id=\"guild-cs\">
            	{$this->lang->words['Home']['CastleSiege']['Owner']} 
                <a href=\"javascript: void(0);\" class=\"guildLink\" rel=\"{$home_module['CastleSiege']['GuildName']}\">{$home_module['CastleSiege']['guildName']}</a>
            </p>
        	<p id=\"date-cs\">
                {$this->lang->words['Home']['CastleSiege']['NextInvasion']} 
                <span class=\"blue-ocean\">{$home_module['CastleSiege']['invasionDate']} - {$home_module['CastleSiege']['invasionHour']}</span>
            </p>
            <img src=\"{$home_module['CastleSiege']['guildMark']}\" class=\"guild-mark\" alt=\"{$home_module['CastleSiege']['guildName']} - Logo\">
        </div>
    </div>" : NULL)."
    
    ".($home_module['rankingData'] != 'NONE_RANK' ? "<div class=\"box-content\">
    	<div class=\"header\"><span>{$this->lang->words['Home']['TopRank']['Title']}</span></div>
        <table width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"3\" class=\"optionSelect\">
        	<tr>
            	".($this->settings['HOME']['TOP_RANK']['RESETS'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"ResetsGeneral\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['Resets']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['R_DAILY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"ResetsDaily\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['RDaily']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['R_WEEKLY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"ResetsWeekly\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['RWeekly']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['R_MONTHLY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"ResetsMonthly\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['RMonthly']}</strong></td>" : NULL)."
			</tr>
        </table>
        <table width=\"100%\" border=\"0\" cellpadding=\"7\" cellspacing=\"0\">
        	<tr>
            	<td width=\"20%\" valign=\"top\">
                	<table width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"3\" class=\"optionSelect\">
                    	".($this->settings['HOME']['TOP_RANK']['LEVEL'][0] == true ? "<tr>
                        	<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"RankLevel\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['Level']}</strong></td>
        				</tr>" : NULL)."
                        ".($this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][0] == true ? "<tr>
                        	<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"RankMLevel\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['MLevel']}</strong></td>
        				</tr>" : NULL)."
                        ".($this->settings['HOME']['TOP_RANK']['PK_KILLS'][0] == true ? "<tr>
                        	<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"PkKills\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['PkKills']}</strong></td>
                        </tr>" : NULL)."
                        ".($this->settings['HOME']['TOP_RANK']['HERO_KILLS'][0] == true ? "<tr>
                        	<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"HeroKills\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['HeroKills']}</strong></td>
                        </tr>" : NULL)."
                        ".($this->settings['HOME']['TOP_RANK']['GUILDS'][0] == true ? "<tr>
                        	<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"Guilds\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['Guilds']}</strong></td>
                        </tr>" : NULL)."
        			</table>
        		</td>
                <td width=\"80%\" valign=\"top\">
                	".($this->settings['HOME']['TOP_RANK']['RESETS'][0] == true ? "".$this->includes_toprank_resets()."" : NULL)."
					".($this->settings['HOME']['TOP_RANK']['R_DAILY'][0] == true ? "".$this->includes_toprank_rdaily()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['R_WEEKLY'][0] == true ? "".$this->includes_toprank_rweekly()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['R_MONTHLY'][0] == true ? "".$this->includes_toprank_rmonthly()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['MRESETS'][0] == true ? "".$this->includes_toprank_mresets()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['MR_DAILY'][0] == true ? "".$this->includes_toprank_mrdaily()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][0] == true ? "".$this->includes_toprank_mrweekly()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][0] == true ? "".$this->includes_toprank_mrmonthly()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['LEVEL'][0] == true ? "".$this->includes_toprank_level()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][0] == true ? "".$this->includes_toprank_mlevel()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['PK_KILLS'][0] == true ? "".$this->includes_toprank_pkkills()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['HERO_KILLS'][0] == true ? "".$this->includes_toprank_herokills()."" : NULL)."
                    ".($this->settings['HOME']['TOP_RANK']['GUILDS'][0] == true ? "".$this->includes_toprank_guilds()."" : NULL)."
                </td>
        	</tr>
        </table>
        <table width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"3\" class=\"optionSelect\">
        	<tr>
            	".($this->settings['HOME']['TOP_RANK']['MRESETS'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"MResetsGeneral\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['MResets']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['MR_DAILY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"MResetsDaily\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['MRDaily']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"MResetsWeekly\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['MRWeekly']}</strong></td>" : NULL)."
                ".($this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][0] == true ? "<td height=\"33\" align=\"center\" rel=\"SelectRanking\" id=\"MResetsMonthly\"><strong>{$this->lang->words['Home']['TopRank']['Ranks']['MRMonthly']}</strong></td>" : NULL)."
			</tr>
        </table>
        ".($this->settings['WEBCACHE']['RANKINGS']['SWITCH'] == true ? "<div class=\"right\"><strong><i>{$this->lang->words['Home']['TopRank']['Cache']}</i></strong></div>" : NULL)."
    </div>" : NULL)."";
		return $CTM_HTML;
	}
	//============================================
	// End: homePage
	//============================================
	//============================================
	// Begin: includes_toprank_guilds
	//============================================
	public function includes_toprank_guilds() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_Guilds\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['guilds']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['GUILDS'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_guilds__0x02()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Score']}</span>
                            </li>
                            ".$this->loop__includes_toprank_guilds__0x03()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_guilds
	//============================================
	//============================================
	// Begin: includes_toprank_herokills
	//============================================
	public function includes_toprank_herokills() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_HeroKills\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['heroKills']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['HERO_KILLS'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_herokills__0x04()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['HeroKills']}</span>
                            </li>
                            ".$this->loop__includes_toprank_herokills__0x05()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_herokills
	//============================================
	//============================================
	// Begin: includes_toprank_level
	//============================================
	public function includes_toprank_level() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_RankLevel\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['level']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['LEVEL'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_level__0x06()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Level']}</span>
                            </li>
                            ".$this->loop__includes_toprank_level__0x07()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_level
	//============================================
	//============================================
	// Begin: includes_toprank_mlevel
	//============================================
	public function includes_toprank_mlevel() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_RankMLevel\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['masterLevel']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_mlevel__0x08()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['MLevel']}</span>
                            </li>
                            ".$this->loop__includes_toprank_mlevel__0x09()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_mlevel
	//============================================
	//============================================
	// Begin: includes_toprank_mrdaily
	//============================================
	public function includes_toprank_mrdaily() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_MResetsDaily\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['mresetsDaily']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['MR_DAILY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_mrdaily__0x0A()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['MRDaily']}</span>
                            </li>
                            ".$this->loop__includes_toprank_mrdaily__0x0B()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_mrdaily
	//============================================
	//============================================
	// Begin: includes_toprank_mresets
	//============================================
	public function includes_toprank_mresets() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_MResetsGeneral\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['mresetsGeneral']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['MRESETS'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_mresets__0x0C()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['MResets']}</span>
                            </li>
                            ".$this->loop__includes_toprank_mresets__0x0D()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_mresets
	//============================================
	//============================================
	// Begin: includes_toprank_mrmonthly
	//============================================
	public function includes_toprank_mrmonthly() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_MResetsMonthly\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['mresetsMonthly']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_mrmonthly__0x0E()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['MRMonthly']}</span>
                            </li>
                            ".$this->loop__includes_toprank_mrmonthly__0x0F()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_mrmonthly
	//============================================
	//============================================
	// Begin: includes_toprank_mrweekly
	//============================================
	public function includes_toprank_mrweekly() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_MResetsWeekly\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['mresetsWeekly']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_mrweekly__0x10()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['MRWeekly']}</span>
                            </li>
                            ".$this->loop__includes_toprank_mrweekly__0x11()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_mrweekly
	//============================================
	//============================================
	// Begin: includes_toprank_pkkills
	//============================================
	public function includes_toprank_pkkills() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_PkKills\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['pkKills']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['PK_KILLS'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_pkkills__0x12()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['PkKills']}</span>
                            </li>
                            ".$this->loop__includes_toprank_pkkills__0x13()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_pkkills
	//============================================
	//============================================
	// Begin: includes_toprank_rdaily
	//============================================
	public function includes_toprank_rdaily() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_ResetsDaily\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['resetsDaily']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['R_DAILY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_rdaily__0x14()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['RDaily']}</span>
                            </li>
                            ".$this->loop__includes_toprank_rdaily__0x15()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_rdaily
	//============================================
	//============================================
	// Begin: includes_toprank_resets
	//============================================
	public function includes_toprank_resets() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_ResetsGeneral\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['resetsGeneral']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['RESETS'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_resets__0x16()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Resets']}</span>
                            </li>
                            ".$this->loop__includes_toprank_resets__0x17()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_resets
	//============================================
	//============================================
	// Begin: includes_toprank_rmonthly
	//============================================
	public function includes_toprank_rmonthly() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_ResetsMonthly\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['resetsMonthly']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['R_MONTHLY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_rmonthly__0x18()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['RMonthly']}</span>
                            </li>
                            ".$this->loop__includes_toprank_rmonthly__0x19()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_rmonthly
	//============================================
	//============================================
	// Begin: includes_toprank_rweekly
	//============================================
	public function includes_toprank_rweekly() 
	{
		global $home_module;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "                	<div id=\"Ranking_ResetsWeekly\" class=\"currentRanking\">
                    	".(count($home_module['rankings']['resetsWeekly']) > 0 ? "".($this->settings['HOME']['TOP_RANK']['R_WEEKLY'][2] == true ? "<ul class=\"topRanks\">
                        	".$this->loop__includes_toprank_rweekly__0x1A()."
                		</ul>" : "<ul class=\"ranks-classic\">
                            <li>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{$this->lang->words['Home']['TopRank']['Words']['RWeekly']}</span>
                            </li>
                            ".$this->loop__includes_toprank_rweekly__0x1B()."
                        </ul>")."" : NULL)."
               		</div>";
		return $CTM_HTML;
	}
	//============================================
	// End: includes_toprank_rweekly
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* homePage : 0x00 */
	private function loop__homePage__0x00()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['webNotices']) > 0)
		{
			foreach($home_module['webNotices'] as $n)
			{
				$content .= "<li>&raquo; <a href=\"javascript: void(0);\" onclick=\"CTM.Load('?/notices/view/{$n['id']}','content');\">{$n['title']}</a> - [ {$n['post_date']} ]</li>
            ";
			}
		}
		return rtrim($content);
	}
	/* homePage : 0x01 */
	private function loop__homePage__0x01()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['forumNotices']) > 0)
		{
			foreach($home_module['forumNotices'] as $forumNotices)
			{
				$content .= "<li>&raquo; <a href=\"{$forumNotices['topicLink']}\"{$this->tmp_vars['target']}>{$forumNotices['title']}</a> - [ {$forumNotices['postDate']} ]</li>
            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_guilds : 0x02 */
	private function loop__includes_toprank_guilds__0x02()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['guilds']) > 0)
		{
			foreach($home_module['rankings']['guilds'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"guildLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$this->lang->words['Home']['TopRank']['Words']['Score']}: {$rank['result']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_guilds : 0x03 */
	private function loop__includes_toprank_guilds__0x03()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['guilds']) > 0)
		{
			foreach($home_module['rankings']['guilds'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"guildLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_herokills : 0x04 */
	private function loop__includes_toprank_herokills__0x04()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['heroKills']) > 0)
		{
			foreach($home_module['rankings']['heroKills'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['HeroKills']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_herokills : 0x05 */
	private function loop__includes_toprank_herokills__0x05()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['heroKills']) > 0)
		{
			foreach($home_module['rankings']['heroKills'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_level : 0x06 */
	private function loop__includes_toprank_level__0x06()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['level']) > 0)
		{
			foreach($home_module['rankings']['level'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$this->lang->words['Home']['TopRank']['Words']['Level']}: {$rank['result']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_level : 0x07 */
	private function loop__includes_toprank_level__0x07()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['level']) > 0)
		{
			foreach($home_module['rankings']['level'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mlevel : 0x08 */
	private function loop__includes_toprank_mlevel__0x08()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['masterLevel']) > 0)
		{
			foreach($home_module['rankings']['masterLevel'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$this->lang->words['Home']['TopRank']['Words']['MLevel']}: {$rank['result']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mlevel : 0x09 */
	private function loop__includes_toprank_mlevel__0x09()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['masterLevel']) > 0)
		{
			foreach($home_module['rankings']['masterLevel'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrdaily : 0x0A */
	private function loop__includes_toprank_mrdaily__0x0A()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsDaily']) > 0)
		{
			foreach($home_module['rankings']['mresetsDaily'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['MRDaily']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrdaily : 0x0B */
	private function loop__includes_toprank_mrdaily__0x0B()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsDaily']) > 0)
		{
			foreach($home_module['rankings']['mresetsDaily'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mresets : 0x0C */
	private function loop__includes_toprank_mresets__0x0C()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsGeneral']) > 0)
		{
			foreach($home_module['rankings']['mresetsGeneral'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['MResets']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mresets : 0x0D */
	private function loop__includes_toprank_mresets__0x0D()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsGeneral']) > 0)
		{
			foreach($home_module['rankings']['mresetsGeneral'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrmonthly : 0x0E */
	private function loop__includes_toprank_mrmonthly__0x0E()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsMonthly']) > 0)
		{
			foreach($home_module['rankings']['mresetsMonthly'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['MRMonthly']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrmonthly : 0x0F */
	private function loop__includes_toprank_mrmonthly__0x0F()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsMonthly']) > 0)
		{
			foreach($home_module['rankings']['mresetsMonthly'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrweekly : 0x10 */
	private function loop__includes_toprank_mrweekly__0x10()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsWeekly']) > 0)
		{
			foreach($home_module['rankings']['mresetsWeekly'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['MRWeekly']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_mrweekly : 0x11 */
	private function loop__includes_toprank_mrweekly__0x11()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['mresetsWeekly']) > 0)
		{
			foreach($home_module['rankings']['mresetsWeekly'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_pkkills : 0x12 */
	private function loop__includes_toprank_pkkills__0x12()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['pkKills']) > 0)
		{
			foreach($home_module['rankings']['pkKills'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['PkKills']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_pkkills : 0x13 */
	private function loop__includes_toprank_pkkills__0x13()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['pkKills']) > 0)
		{
			foreach($home_module['rankings']['pkKills'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rdaily : 0x14 */
	private function loop__includes_toprank_rdaily__0x14()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsDaily']) > 0)
		{
			foreach($home_module['rankings']['resetsDaily'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['RDaily']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rdaily : 0x15 */
	private function loop__includes_toprank_rdaily__0x15()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsDaily']) > 0)
		{
			foreach($home_module['rankings']['resetsDaily'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_resets : 0x16 */
	private function loop__includes_toprank_resets__0x16()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsGeneral']) > 0)
		{
			foreach($home_module['rankings']['resetsGeneral'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['Resets']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_resets : 0x17 */
	private function loop__includes_toprank_resets__0x17()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsGeneral']) > 0)
		{
			foreach($home_module['rankings']['resetsGeneral'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rmonthly : 0x18 */
	private function loop__includes_toprank_rmonthly__0x18()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsMonthly']) > 0)
		{
			foreach($home_module['rankings']['resetsMonthly'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['RMonthly']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rmonthly : 0x19 */
	private function loop__includes_toprank_rmonthly__0x19()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsMonthly']) > 0)
		{
			foreach($home_module['rankings']['resetsMonthly'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rweekly : 0x1A */
	private function loop__includes_toprank_rweekly__0x1A()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsWeekly']) > 0)
		{
			foreach($home_module['rankings']['resetsWeekly'] as $rank)
			{
				$content .= "<li>
                            	<a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm; - {$rank['name']}</span>
                                    <img src=\"{$rank['image']}\" alt=\"{$rank['name']}\">
                                </a>
                                <span>( {$rank['result']} {$this->lang->words['Home']['TopRank']['Words']['RWeekly']} )</span>
                			</li>
                            ";
			}
		}
		return rtrim($content);
	}
	/* includes_toprank_rweekly : 0x1B */
	private function loop__includes_toprank_rweekly__0x1B()
	{
		global $home_module; // PHP Globals
		$content = NULL;

		if(count($home_module['rankings']['resetsWeekly']) > 0)
		{
			foreach($home_module['rankings']['resetsWeekly'] as $rank)
			{
				$content .= "<li>
                                <a href=\"javascript: void(0);\" class=\"rankLink\" rel=\"{$rank['name']}\">
                                    <span>{$rank['order']}&ordm;</span>
                                    <span>{$rank['name']}</span>
                                    <span>{$rank['result']}</span>
                                </a>
                            </li>
                            ";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_home();
$callSkinCache->registry();