<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Cache file:                                             */
/* Cache generated in 14/09/2013 - 17:40h                  */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.10.15    */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the database automatically */
/***********************************************************/

class skin_ajax extends CTM_Command
{
	//============================================
	// Begin: GameMasters
	//============================================
	public function GameMasters() 
	{
		global $ajax_gamemasters;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "".(count($ajax_gamemasters) > 0 ? "<ul class=\"info\">
	".$this->loop__GameMasters__0x00()."
</ul>" : "<div class=\"info-min\">{$this->lang->words['Ajax']['GameMasters']['Message']}</div>")."";
		return $CTM_HTML;
	}
	//============================================
	// End: GameMasters
	//============================================
	//============================================
	// Begin: WebPoll_All
	//============================================
	public function WebPoll_All() 
	{
		$CTM_HTML = NULL;
		$CTM_HTML .= "<ul class=\"info\">
	".$this->loop__WebPoll_All__0x01()."
</ul>";
		return $CTM_HTML;
	}
	//============================================
	// End: WebPoll_All
	//============================================
	//============================================
	// Begin: WebPoll_Result
	//============================================
	public function WebPoll_Result() 
	{
		global $ajax_poll_result;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "<ul class=\"info\">
	<li><span>{$this->lang->words['Ajax']['Poll']['Status']} </span>{$ajax_poll_result['status']}</li>
    <li><span>{$this->lang->words['Ajax']['Poll']['Total']} </span>{$ajax_poll_result['total_votes']}</li>
    <li><span>{$this->lang->words['Ajax']['Poll']['BeginDate']} </span>{$ajax_poll_result['begin_date']}</li>
    <li><span>{$this->lang->words['Ajax']['Poll']['EndDate']} </span>{$ajax_poll_result['end_date']}</li>
    <li class=\"line\"><!-- Separator line --></li>
    ".$this->loop__WebPoll_Result__0x02()."
</ul>
".(!empty($ajax_poll_result['message']) ? "<div style=\"clear: both;\"></div>
{$ajax_poll_result['message']}" : NULL)."";
		return $CTM_HTML;
	}
	//============================================
	// End: WebPoll_Result
	//============================================
	//============================================
	// Begin: WebPoll_Show
	//============================================
	public function WebPoll_Show() 
	{
		global $ajax_poll;  // PHP Globals

		$CTM_HTML = NULL;
		$CTM_HTML .= "<ul class=\"info\">
	<li><span>{$ajax_poll['question']}</span></li>
	<li class=\"line\"><!-- Separator line --></li>
    <form name=\"AjaxPoll\" id=\"AjaxPoll\">
    ".$this->loop__WebPoll_Show__0x03()."
	<li class=\"line\"><!-- Separator line --></li>
		<input type=\"button\" class=\"btn\" value=\"{$this->lang->words['Ajax']['Poll']['Vote']}\" onclick=\"CTM.AjaxLoad('?app=core&amp;ajax=poll&amp;cmd=vote&amp;id={$ajax_poll['id']}', 'PollResult', 'AjaxPoll');\" />
		<input type=\"button\" class=\"btn\" value=\"{$this->lang->words['Ajax']['Poll']['Result']}\" onclick=\"CTM.AjaxLoad('?app=core&amp;ajax=poll&amp;cmd=result&amp;id={$ajax_poll['id']}', 'PollResult');\" />
	</form>
    <li><span><a href=\"javascript: void(0);\" onclick=\"CTM.AjaxLoad('?app=core&ajax=poll&cmd=loadPolls', 'WebAjaxPoll');\">{$this->lang->words['Ajax']['Poll']['All']}</a></span></li>
</ul>
<div id=\"PollResult\"></div>";
		return $CTM_HTML;
	}
	//============================================
	// End: WebPoll_Show
	//============================================

	//============================================
	// Begin: Foreach functions
	//============================================
	/* GameMasters : 0x00 */
	private function loop__GameMasters__0x00()
	{
		global $ajax_gamemasters; // PHP Globals
		$content = NULL;

		if(count($ajax_gamemasters) > 0)
		{
			foreach($ajax_gamemasters as $gm)
			{
				$content .= "<li>
    	<span>{$gm['name']} - </span>
        ".($gm['status'] == 1 ? "<span class=\"green\">Online</span>" : "<span class=\"red\">Offline</span>")."
	</li>
    ";
			}
		}
		return rtrim($content);
	}
	/* WebPoll_All : 0x01 */
	private function loop__WebPoll_All__0x01()
	{
		global $ajax_all_polls; // PHP Globals
		$content = NULL;

		if(count($ajax_all_polls) > 0)
		{
			foreach($ajax_all_polls as $id => $question)
			{
				$content .= "<li><span><a href=\"javascript: void(0);\" onclick=\"CTM.AjaxLoad('?ajax=poll&id={$id}','WebAjaxPoll');\">{$question}</a></span></li>
    ";
			}
		}
		return rtrim($content);
	}
	/* WebPoll_Result : 0x02 */
	private function loop__WebPoll_Result__0x02()
	{
		global $ajax_poll_result; // PHP Globals
		$content = NULL;

		if(count($ajax_poll_result['answers']) > 0)
		{
			foreach($ajax_poll_result['answers'] as $id => $data)
			{
				$content .= "<li>
    	<span>{$data['answer']} - </span>
        {$this->lang->words['Ajax']['Poll']['Votes']} <strong>{$data['votes']}</strong> (<strong>{$data['result']}%</strong>)<br />
        <div class=\"border-bar\">
        	<div class=\"green-gauge\" style=\"width: {$data['result']}%\"><!-- Bar --></div>
		</div>
    </li>
    ";
			}
		}
		return rtrim($content);
	}
	/* WebPoll_Show : 0x03 */
	private function loop__WebPoll_Show__0x03()
	{
		global $ajax_poll; // PHP Globals
		$content = NULL;

		if(count($ajax_poll['answers']) > 0)
		{
			foreach($ajax_poll['answers'] as $id => $answer)
			{
				$content .= "<li><input type=\"radio\" name=\"PollAnswer\" id=\"PollAnswer\" value=\"{$id}\">&nbsp; {$answer}</li>
    ";
			}
		}
		return rtrim($content);
	}
	//============================================
	// End: Foreach functions
	//============================================
}
$callSkinCache = new skin_ajax();
$callSkinCache->registry();