<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_ajax                                      */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: GameMasters **********/
$CTM_TEMPLATE_DATABASE['GameMasters'] = <<<HTML
<if syntax="count(::x####$####x::ajax_gamemasters) > 0">
<ul class="info">
	<foreach loop="::x####$####x::ajax_gamemasters as ::x####$####x::gm">
	<li>
    	<span>{::x####$####x::gm['name']} - </span>
        <if syntax="::x####$####x::gm['status'] == 1"><span class="green">Online</span><else /><span class="red">Offline</span></if>
	</li>
    </foreach>
</ul>
<else />
<div class="info-min">{::x####$####x::this->lang->words['Ajax']['GameMasters']['Message']}</div>
</if>
HTML;
/********** End: GameMasters **********/

/********** Begin: WebPoll_All **********/
$CTM_TEMPLATE_DATABASE['WebPoll_All'] = <<<HTML
<ul class="info">
	<foreach loop="::x####$####x::ajax_all_polls as ::x####$####x::id => ::x####$####x::question">
	<li><span><a href="javascript: void(0);" onclick="CTM.AjaxLoad('?ajax=poll&id={::x####$####x::id}','WebAjaxPoll');">{::x####$####x::question}</a></span></li>
    </foreach>
</ul>
HTML;
/********** End: WebPoll_All **********/

/********** Begin: WebPoll_Result **********/
$CTM_TEMPLATE_DATABASE['WebPoll_Result'] = <<<HTML
<ul class="info">
	<li><span>{::x####$####x::this->lang->words['Ajax']['Poll']['Status']} </span>{::x####$####x::ajax_poll_result['status']}</li>
    <li><span>{::x####$####x::this->lang->words['Ajax']['Poll']['Total']} </span>{::x####$####x::ajax_poll_result['total_votes']}</li>
    <li><span>{::x####$####x::this->lang->words['Ajax']['Poll']['BeginDate']} </span>{::x####$####x::ajax_poll_result['begin_date']}</li>
    <li><span>{::x####$####x::this->lang->words['Ajax']['Poll']['EndDate']} </span>{::x####$####x::ajax_poll_result['end_date']}</li>
    <li class="line"><!-- Separator line --></li>
    <foreach loop="::x####$####x::ajax_poll_result['answers'] as ::x####$####x::id => ::x####$####x::data">
    <li>
    	<span>{::x####$####x::data['answer']} - </span>
        {::x####$####x::this->lang->words['Ajax']['Poll']['Votes']} <strong>{::x####$####x::data['votes']}</strong> (<strong>{::x####$####x::data['result']}%</strong>)<br />
        <div class="border-bar">
        	<div class="green-gauge" style="width: {::x####$####x::data['result']}%"><!-- Bar --></div>
		</div>
    </li>
    </foreach>
</ul>
<if syntax="!empty(::x####$####x::ajax_poll_result['message'])">
<div style="clear: both;"></div>
{::x####$####x::ajax_poll_result['message']}
</if>
HTML;
/********** End: WebPoll_Result **********/

/********** Begin: WebPoll_Show **********/
$CTM_TEMPLATE_DATABASE['WebPoll_Show'] = <<<HTML
<ul class="info">
	<li><span>{::x####$####x::ajax_poll['question']}</span></li>
	<li class="line"><!-- Separator line --></li>
    <form name="AjaxPoll" id="AjaxPoll">
    <foreach loop="::x####$####x::ajax_poll['answers'] as ::x####$####x::id => ::x####$####x::answer">
	<li><input type="radio" name="PollAnswer" id="PollAnswer" value="{::x####$####x::id}">&nbsp; {::x####$####x::answer}</li>
    </foreach>
	<li class="line"><!-- Separator line --></li>
		<input type="button" class="btn" value="{::x####$####x::this->lang->words['Ajax']['Poll']['Vote']}" onclick="CTM.AjaxLoad('?app=core&amp;ajax=poll&amp;cmd=vote&amp;id={::x####$####x::ajax_poll['id']}', 'PollResult', 'AjaxPoll');" />
		<input type="button" class="btn" value="{::x####$####x::this->lang->words['Ajax']['Poll']['Result']}" onclick="CTM.AjaxLoad('?app=core&amp;ajax=poll&amp;cmd=result&amp;id={::x####$####x::ajax_poll['id']}', 'PollResult');" />
	</form>
    <li><span><a href="javascript: void(0);" onclick="CTM.AjaxLoad('?app=core&ajax=poll&cmd=loadPolls', 'WebAjaxPoll');">{::x####$####x::this->lang->words['Ajax']['Poll']['All']}</a></span></li>
</ul>
<div id="PollResult"></div>
HTML;
/********** End: WebPoll_Show **********/