<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_home                                      */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: homePage **********/
$CTM_TEMPLATE_DATABASE['homePage'] = <<<HTML
	<if syntax="::x####$####x::home_module['rankingData'] != 'NONE_RANK'">
	<script type="text/javascript">
	::x####$####x::(function()
	{
		::x####$####x::("td[rel*=SelectRanking]").click(function()
		{
			rank = ::x####$####x::(this).attr("id");
	
			::x####$####x::(".currentRanking").hide().ready(function()
			{
				::x####$####x::("#Ranking_"+rank).show("slow"); 
				::x####$####x::("td[rel*=SelectRanking]").attr("class", "");
				::x####$####x::("#"+rank).attr("class", "current");
			});
		});
		::x####$####x::(".currentRanking").hide().ready(function()
		{
			::x####$####x::("#Ranking_{::x####$####x::home_module['rankingData']}").show("slow"); 
			::x####$####x::("#{::x####$####x::home_module['rankingData']}").attr("class", "current");
		});
		::x####$####x::(".rankLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load("?/char/"+charName, "content");
		});
		::x####$####x::(".guildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load("?/guild/"+guildName, "content");
		});
	});
	</script>
    </if>
    <if syntax="::x####$####x::this->settings['HOME']['NOTICES']['SHOW'] == true">
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Home']['Notices']['Title']}</span></div>
        <if syntax="count(::x####$####x::home_module['webNotices']) > 0">
		<ul class="news">
        	<foreach loop="::x####$####x::home_module['webNotices'] as ::x####$####x::n">
        	<li>&raquo; <a href="javascript: void(0);" onclick="CTM.Load('?/notices/view/{::x####$####x::n['id']}','content');">{::x####$####x::n['title']}</a> - [ {::x####$####x::n['post_date']} ]</li>
            </foreach>
        </ul>
        <div class="right"><a href="javascript: void(0);" onclick="CTM.Load('?/notices','content');">[ {::x####$####x::this->lang->words['Home']['Notices']['All']} ]</a></div>
        <else />
		<div class="info-box">{::x####$####x::this->lang->words['Home']['Notices']['Void']}</div>
		</if>
    </div>
    </if>
    
    <if syntax="::x####$####x::this->settings['HOME']['FORUM']['SHOW'] == true">
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Home']['ForumNotices']['Title']}</span></div>
        <if syntax="::x####$####x::home_module['forumNotices']">
        <if syntax="count(::x####$####x::home_module['forumNotices']) > 0">
        <php>::x####$####x::this->tmp_vars['target'] = ::x####$####x::this->settings['HOME']['FORUM']['NEW_WINDOW'] == true ? " target=\"_blank\"" : NULL;</php>
		<ul class="news">
        	<foreach loop="::x####$####x::home_module['forumNotices'] as ::x####$####x::forumNotices">
        	<li>&raquo; <a href="{::x####$####x::forumNotices['topicLink']}"{::x####$####x::this->tmp_vars['target']}>{::x####$####x::forumNotices['title']}</a> - [ {::x####$####x::forumNotices['postDate']} ]</li>
            </foreach>
        </ul>
        <else />
		<div class="info-box">{::x####$####x::this->lang->words['Home']['ForumNotices']['Void']}</div>
        </if>
        <else />
        <div class="error-box">{::x####$####x::this->lang->words['Home']['ForumNotices']['Error']}</div>
        </if>
    </div>
    </if>
    
    <if syntax="::x####$####x::this->settings['HOME']['SIEGE']['SHOW'] == true">
    <div class="box-content">
    	<div id="castle-siege">
        	<p id="guild-cs">
            	{::x####$####x::this->lang->words['Home']['CastleSiege']['Owner']} 
                <a href="javascript: void(0);" class="guildLink" rel="{::x####$####x::home_module['CastleSiege']['GuildName']}">{::x####$####x::home_module['CastleSiege']['guildName']}</a>
            </p>
        	<p id="date-cs">
                {::x####$####x::this->lang->words['Home']['CastleSiege']['NextInvasion']} 
                <span class="blue-ocean">{::x####$####x::home_module['CastleSiege']['invasionDate']} - {::x####$####x::home_module['CastleSiege']['invasionHour']}</span>
            </p>
            <img src="{::x####$####x::home_module['CastleSiege']['guildMark']}" class="guild-mark" alt="{::x####$####x::home_module['CastleSiege']['guildName']} - Logo">
        </div>
    </div>
    </if>
    
    <if syntax="::x####$####x::home_module['rankingData'] != 'NONE_RANK'">
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Home']['TopRank']['Title']}</span></div>
        <table width="100%" border="0" cellpadding="10" cellspacing="3" class="optionSelect">
        	<tr>
            	<if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['RESETS'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="ResetsGeneral"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['Resets']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_DAILY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="ResetsDaily"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['RDaily']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_WEEKLY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="ResetsWeekly"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['RWeekly']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_MONTHLY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="ResetsMonthly"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['RMonthly']}</strong></td>
                </if>
			</tr>
        </table>
        <table width="100%" border="0" cellpadding="7" cellspacing="0">
        	<tr>
            	<td width="20%" valign="top">
                	<table width="100%" border="0" cellpadding="10" cellspacing="3" class="optionSelect">
                    	<if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['LEVEL'][0] == true">
                        <tr>
                        	<td height="33" align="center" rel="SelectRanking" id="RankLevel"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['Level']}</strong></td>
        				</tr>
                        </if>
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][0] == true">
                        <tr>
                        	<td height="33" align="center" rel="SelectRanking" id="RankMLevel"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['MLevel']}</strong></td>
        				</tr>
                        </if>
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['PK_KILLS'][0] == true">
                        <tr>
                        	<td height="33" align="center" rel="SelectRanking" id="PkKills"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['PkKills']}</strong></td>
                        </tr>
                        </if>
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['HERO_KILLS'][0] == true">
                        <tr>
                        	<td height="33" align="center" rel="SelectRanking" id="HeroKills"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['HeroKills']}</strong></td>
                        </tr>
                        </if>
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['GUILDS'][0] == true">
                        <tr>
                        	<td height="33" align="center" rel="SelectRanking" id="Guilds"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['Guilds']}</strong></td>
                        </tr>
                        </if>
        			</table>
        		</td>
                <td width="80%" valign="top">
                	<if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['RESETS'][0] == true">{template="includes_toprank_resets"}</if>
					<if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_DAILY'][0] == true">{template="includes_toprank_rdaily"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_WEEKLY'][0] == true">{template="includes_toprank_rweekly"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_MONTHLY'][0] == true">{template="includes_toprank_rmonthly"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MRESETS'][0] == true">{template="includes_toprank_mresets"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_DAILY'][0] == true">{template="includes_toprank_mrdaily"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][0] == true">{template="includes_toprank_mrweekly"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][0] == true">{template="includes_toprank_mrmonthly"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['LEVEL'][0] == true">{template="includes_toprank_level"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][0] == true">{template="includes_toprank_mlevel"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['PK_KILLS'][0] == true">{template="includes_toprank_pkkills"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['HERO_KILLS'][0] == true">{template="includes_toprank_herokills"}</if>
                    <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['GUILDS'][0] == true">{template="includes_toprank_guilds"}</if>
                </td>
        	</tr>
        </table>
        <table width="100%" border="0" cellpadding="10" cellspacing="3" class="optionSelect">
        	<tr>
            	<if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MRESETS'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="MResetsGeneral"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['MResets']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_DAILY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="MResetsDaily"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['MRDaily']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="MResetsWeekly"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['MRWeekly']}</strong></td>
                </if>
                <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][0] == true">
                <td height="33" align="center" rel="SelectRanking" id="MResetsMonthly"><strong>{::x####$####x::this->lang->words['Home']['TopRank']['Ranks']['MRMonthly']}</strong></td>
                </if>
			</tr>
        </table>
        <if syntax="::x####$####x::this->settings['WEBCACHE']['RANKINGS']['SWITCH'] == true">
        <div class="right"><strong><i>{::x####$####x::this->lang->words['Home']['TopRank']['Cache']}</i></strong></div>
        </if>
    </div>
    </if>
HTML;
/********** End: homePage **********/

/********** Begin: includes_toprank_guilds **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_guilds'] = <<<HTML
                	<div id="Ranking_Guilds" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['guilds']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['GUILDS'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['guilds'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="guildLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::this->lang->words['Home']['TopRank']['Words']['Score']}: {::x####$####x::rank['result']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Score']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['guilds'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="guildLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_guilds **********/

/********** Begin: includes_toprank_herokills **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_herokills'] = <<<HTML
                	<div id="Ranking_HeroKills" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['heroKills']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['HERO_KILLS'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['heroKills'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['HeroKills']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['HeroKills']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['heroKills'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_herokills **********/

/********** Begin: includes_toprank_level **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_level'] = <<<HTML
                	<div id="Ranking_RankLevel" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['level']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['LEVEL'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['level'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::this->lang->words['Home']['TopRank']['Words']['Level']}: {::x####$####x::rank['result']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Level']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['level'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_level **********/

/********** Begin: includes_toprank_mlevel **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_mlevel'] = <<<HTML
                	<div id="Ranking_RankMLevel" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['masterLevel']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MASTER_LEVEL'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['masterLevel'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::this->lang->words['Home']['TopRank']['Words']['MLevel']}: {::x####$####x::rank['result']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['MLevel']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['masterLevel'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_mlevel **********/

/********** Begin: includes_toprank_mrdaily **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_mrdaily'] = <<<HTML
                	<div id="Ranking_MResetsDaily" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['mresetsDaily']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_DAILY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['mresetsDaily'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRDaily']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRDaily']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['mresetsDaily'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_mrdaily **********/

/********** Begin: includes_toprank_mresets **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_mresets'] = <<<HTML
                	<div id="Ranking_MResetsGeneral" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['mresetsGeneral']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MRESETS'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['mresetsGeneral'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['MResets']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['MResets']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['mresetsGeneral'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_mresets **********/

/********** Begin: includes_toprank_mrmonthly **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_mrmonthly'] = <<<HTML
                	<div id="Ranking_MResetsMonthly" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['mresetsMonthly']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_MONTHLY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['mresetsMonthly'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRMonthly']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRMonthly']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['mresetsMonthly'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_mrmonthly **********/

/********** Begin: includes_toprank_mrweekly **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_mrweekly'] = <<<HTML
                	<div id="Ranking_MResetsWeekly" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['mresetsWeekly']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['MR_WEEKLY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['mresetsWeekly'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRWeekly']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['MRWeekly']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['mresetsWeekly'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_mrweekly **********/

/********** Begin: includes_toprank_pkkills **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_pkkills'] = <<<HTML
                	<div id="Ranking_PkKills" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['pkKills']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['PK_KILLS'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['pkKills'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['PkKills']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['PkKills']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['pkKills'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_pkkills **********/

/********** Begin: includes_toprank_rdaily **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_rdaily'] = <<<HTML
                	<div id="Ranking_ResetsDaily" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['resetsDaily']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_DAILY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['resetsDaily'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['RDaily']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['RDaily']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['resetsDaily'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_rdaily **********/

/********** Begin: includes_toprank_resets **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_resets'] = <<<HTML
                	<div id="Ranking_ResetsGeneral" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['resetsGeneral']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['RESETS'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['resetsGeneral'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['Resets']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Resets']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['resetsGeneral'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_resets **********/

/********** Begin: includes_toprank_rmonthly **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_rmonthly'] = <<<HTML
                	<div id="Ranking_ResetsMonthly" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['resetsMonthly']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_MONTHLY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['resetsMonthly'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['RMonthly']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['RMonthly']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['resetsMonthly'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_rmonthly **********/

/********** Begin: includes_toprank_rweekly **********/
$CTM_TEMPLATE_DATABASE['includes_toprank_rweekly'] = <<<HTML
                	<div id="Ranking_ResetsWeekly" class="currentRanking">
                    	<if syntax="count(::x####$####x::home_module['rankings']['resetsWeekly']) > 0">
                        <if syntax="::x####$####x::this->settings['HOME']['TOP_RANK']['R_WEEKLY'][2] == true">
                    	<ul class="topRanks">
                        	<foreach loop="::x####$####x::home_module['rankings']['resetsWeekly'] as ::x####$####x::rank">
                        	<li>
                            	<a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm; - {::x####$####x::rank['name']}</span>
                                    <img src="{::x####$####x::rank['image']}" alt="{::x####$####x::rank['name']}">
                                </a>
                                <span>( {::x####$####x::rank['result']} {::x####$####x::this->lang->words['Home']['TopRank']['Words']['RWeekly']} )</span>
                			</li>
                            </foreach>
                		</ul>
                        <else />
                        <ul class="ranks-classic">
                            <li>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Position']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['Name']}</span>
                                <span>{::x####$####x::this->lang->words['Home']['TopRank']['Words']['RWeekly']}</span>
                            </li>
                            <foreach loop="::x####$####x::home_module['rankings']['resetsWeekly'] as ::x####$####x::rank">
                            <li>
                                <a href="javascript: void(0);" class="rankLink" rel="{::x####$####x::rank['name']}">
                                    <span>{::x####$####x::rank['order']}&ordm;</span>
                                    <span>{::x####$####x::rank['name']}</span>
                                    <span>{::x####$####x::rank['result']}</span>
                                </a>
                            </li>
                            </foreach>
                        </ul>
                        </if>
                        </if>
               		</div>
HTML;
/********** End: includes_toprank_rweekly **********/