<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_downloads                                 */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: downloads **********/
$CTM_TEMPLATE_DATABASE['downloads'] = <<<HTML
	<script type="text/javascript">
	::x####$####x::(function()
	{
		::x####$####x::("#DownloadLinks select").change(function()
		{
			value = ::x####$####x::(this).val();
			
			if(value != "None")
			{
				linkOriginal = decodeURIComponent(value);
				window.open(linkOriginal, "Download:"+Math.random());
				::x####$####x::(this).val("None");
			}
		});
	});
	</script>
	<div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Downloads']['Title']}</span></div>
        <form name="DownloadLinks" id="DownloadLinks">
        <foreach loop="::x####$####x::this->settings['DOWNLOADS']['CATEGORYS'] as ::x####$####x::key => ::x####$####x::category">
        <h4>{::x####$####x::category}</h4>
        <table width="100%" class="tableBackColumn">
        	<tr>
            	<td width="118"><strong>{::x####$####x::this->lang->words['Downloads']['Table']['Archive']}</strong></td>
                <td width="194"><strong>{::x####$####x::this->lang->words['Downloads']['Table']['Description']}</strong></td>
                <td width="83"><strong>{::x####$####x::this->lang->words['Downloads']['Table']['Size']}</strong></td>
                <td width="71"><strong>{::x####$####x::this->lang->words['Downloads']['Table']['Link']}</strong></td>
            </tr>
            <foreach loop="::x####$####x::this->settings['DOWNLOADS']['ARCHIVES'][::x####$####x::key] as ::x####$####x::file_key => ::x####$####x::FILE">
            <tr>
            	<td>{::x####$####x::FILE['NAME']}</td>
                <td>{::x####$####x::FILE['DESC']}</td>
                <td>{::x####$####x::FILE['SIZE']}</td>
                <td>
                	<select name="DownLinks_{::x####$####x::key}_{::x####$####x::file_key}" id="DownLinks_{::x####$####x::key}_{::x####$####x::file_key}" class="selectField">
                    	<option value="None" selected="selected">{::x####$####x::this->lang->words['Words']['Select']}</option>
                        <foreach loop="::x####$####x::this->settings['DOWNLOADS']['ARCHIVES'][::x####$####x::key][::x####$####x::file_key]['LINK'] as ::x####$####x::i => ::x####$####x::l">
                        <php>::x####$####x::l = urlencode(::x####$####x::l);</php>
                        <option value="{::x####$####x::l}">{::x####$####x::this->lang->words['Downloads']['Table']['Option']} #{::x####$####x::i}</option>
                        </foreach>
            		</select>
            	</td>
            </tr>
            </foreach>
		</table><br />
        </foreach>
        </form>
        <h4>{::x####$####x::this->lang->words['Downloads']['Requirements']['Title']}</h4>
        <table width="100%" class="tableBackColumn">
        	<tr>
            	<td width="118"><strong>{::x####$####x::this->lang->words['Downloads']['Requirements']['Device']}</strong></td>
                <td width="194"><strong>{::x####$####x::this->lang->words['Downloads']['Requirements']['Minimum']}</strong></td>
                <td width="83"><strong>{::x####$####x::this->lang->words['Downloads']['Requirements']['Recommended']}</strong></td>
            </tr>
            <tr>
            	<td width="118">{::x####$####x::this->lang->words['Downloads']['Requirements']['Processor'][0]}</td>
                <td width="118">{::x####$####x::this->lang->words['Downloads']['Requirements']['Processor'][1]}</td>
                <td width="118">{::x####$####x::this->lang->words['Downloads']['Requirements']['Processor'][2]}</td>
            </tr>
            <tr>
            	<td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['Memory'][0]}</td>
                <td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['Memory'][1]}</td>
                <td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['Memory'][2]}</td>
            </tr>
            <tr>
            	<td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['OperationSystem'][0]}</td>
                <td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['OperationSystem'][1]}</td>
                <td width="194">{::x####$####x::this->lang->words['Downloads']['Requirements']['OperationSystem'][2]}</td>
            </tr>
            <tr>
            	<td width="83">{::x####$####x::this->lang->words['Downloads']['Requirements']['Graphics'][0]}</td>
                <td width="83">{::x####$####x::this->lang->words['Downloads']['Requirements']['Graphics'][1]}</td>
                <td width="83">{::x####$####x::this->lang->words['Downloads']['Requirements']['Graphics'][2]}</td>
        	</tr>
        </table><br />
        <h4>{::x####$####x::this->lang->words['Downloads']['Drivers']}</h4>
        <div align="center" class="setQuote">
        	<ul id="drivers">
            	<li id="ati"><a target="_black" href="http://support.amd.com/us/gpudownload/Pages/index.aspx"></a></li>
                <li id="intel"><a target="_black" href="http://downloadcenter.intel.com/"></a></li>
                <li id="matrox"><a target="_black" href="http://www.matrox.com/mga/support/drivers/"></a></li>
                <li id="nvidia"><a target="_black" href="http://www.nvidia.com/Download/index.aspx"></a></li>
			</ul>
    	</div>
    </div>
HTML;
/********** End: downloads **********/