<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_informations                              */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: include_masterResetTable **********/
$CTM_TEMPLATE_DATABASE['include_masterResetTable'] = <<<HTML
<table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
            <thead>
                <tr width="100%">
                    <th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
                </tr>
            </thead>
            <tbody>
            	<if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] < 3">
            	<tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ResetsRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['resets_require'][5]}</td>
                    </if>
                </tr>
                </if>
            	<tr>
                	<td>{::x####$####x::this->lang->words['Infos']['MResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['StrengthRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['strength_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['DexterityRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['dexterity_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['VitalityRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['vitality_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['EnergyRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['energy_require']}</td>
                    </if>
                </tr>
                <if syntax="MUSERVER_VERSION >= 1">
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['CommandRequire']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['command_require']}</td>
                    </if>
                </tr>
                </if>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['money_require'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] == 1">
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ResetsRemove']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['resets_remove'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ResetPoints']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['reset_points'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['Infos']['MResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['clear_quest'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td style="color:#FF0000">{::x####$####x::this->lang->words['Infos']['MResetTable']['CoinAward']}</td>
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][0]}</td>
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['masterResetTable']['coin_award'][5]}</td>
                    </if>
                </tr>
            </tbody>
        </table>
HTML;
/********** End: include_masterResetTable **********/

/********** Begin: include_resetTable **********/
$CTM_TEMPLATE_DATABASE['include_resetTable'] = <<<HTML
<if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] < 4">
        <table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
        	<thead>
            	<tr width="100%">
                	<th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::informations['resetTable']['level_reset'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::informations['resetTable']['money_require'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['money_require'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['LevelAfter']}</td>
                    <td>{::x####$####x::informations['resetTable']['level_after'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['level_after'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['level_after'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['level_after'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['level_after'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['level_after'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0">
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['SetPoints']}</td>
                    <td>{::x####$####x::informations['resetTable']['set_points'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['set_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['set_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['set_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['set_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['set_points'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][0]}</td>
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::informations['resetTable']['clear_quest'][5]}</td>
                    </if>
                </tr>
			</tbody>
		</table>
        <else />
        <foreach loop="::x####$####x::informations['resetTable'] as ::x####$####x::key => ::x####$####x::table">
        <h4>{::x####$####x::this->lang->words['Infos']['ResetTable']['Table']} {::x####$####x::key}</h4>
        <table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
        	<thead>
            	<tr width="100%">
                	<th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::table['level_reset'][0]}</td>
                    <td>{::x####$####x::table['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::table['money_require'][0]}</td>
                    <td>{::x####$####x::table['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['money_require'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['LevelAfter']}</td>
                    <td>{::x####$####x::table['level_after'][0]}</td>
                    <td>{::x####$####x::table['level_after'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['level_after'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['level_after'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['level_after'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['level_after'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0">
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['SetPoints']}</td>
                    <td>{::x####$####x::table['set_points'][0]}</td>
                    <td>{::x####$####x::table['set_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['set_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['set_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['set_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['set_points'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::table['clear_invent'][0]}</td>
                    <td>{::x####$####x::table['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::table['clear_skill'][0]}</td>
                    <td>{::x####$####x::table['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['Infos']['ResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::table['clear_quest'][0]}</td>
                    <td>{::x####$####x::table['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_quest'][5]}</td>
                    </if>
                </tr>
			</tbody>
		</table>
        </foreach>
        </if>
HTML;
/********** End: include_resetTable **********/

/********** Begin: serverInfos **********/
$CTM_TEMPLATE_DATABASE['serverInfos'] = <<<HTML
	<div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Infos']['Title']}</span></div>
        <ul class="info">
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Name']} </span>{const="SERVER_NAME"}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Version']} </span>{const="SERVER_VERSION"}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Experience']} </span>{const="SERVER_EXPERIENCE"}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Drop']} </span>{const="SERVER_DROP"}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['BugBless']} </span>{::x####$####x::this->vars['sidebar']['infos']['bug_bless']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['ResetType']} </span>{::x####$####x::this->vars['sidebar']['infos']['reset_type']}</li>
            <li class="line"><!-- Separator line --></li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['Accounts']} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalAccounts']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['Characters']} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalCharacters']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['Guilds']} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalGuilds']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['AccountsVIP'][1]} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalVIPAccounts'][1]}</li>
            <if syntax="VIP_NUMBER >= 2">
            <li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['AccountsVIP'][2]} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalVIPAccounts'][2]}</li>
            </if>
            <if syntax="VIP_NUMBER >= 3">
            <li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['AccountsVIP'][3]} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalVIPAccounts'][3]}</li>
            </if>
            <if syntax="VIP_NUMBER >= 4">
            <li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['AccountsVIP'][4]} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalVIPAccounts'][4]}</li>
            </if>
            <if syntax="VIP_NUMBER == 5">
            <li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['AccountsVIP'][5]} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalVIPAccounts'][5]}</li>
            </if>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['Banned']['Accounts']} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalBanned']['accounts']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['Count']['Banned']['Characters']} </span>{::x####$####x::this->vars['sidebar']['infos']['count']['totalBanned']['characters']}</li>
            <li><span>{::x####$####x::this->lang->words['Infos']['Count']['CharsPk']} </span>{::x####$####x::informations['count']['chars_pk']}</li>
            <li><span>{::x####$####x::this->lang->words['Infos']['Count']['CharsHero']} </span>{::x####$####x::informations['count']['chars_hero']}</li>
            <li class="line"><!-- Separator line --></li>
            <if syntax="SERVER_STATUS > 0">
            <li><span>{::x####$####x::this->lang->words['Infos']['Status']} </span>{::x####$####x::informations['status']}</li>
            </if>
            <li><span>{::x####$####x::this->lang->words['Infos']['Count']['Onlines']} </span>{::x####$####x::global_serverlist['totalOnline']}</li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['RecordOnline']['Info']['General']} </span><strong>{::x####$####x::this->vars['sidebar']['infos']['recordOnline']['general']}</strong></li>
        	<li><span>{::x####$####x::this->lang->words['Sidebar']['Infos']['RecordOnline']['Info']['Today']} </span><strong>{::x####$####x::this->vars['sidebar']['infos']['recordOnline']['today']}</strong></li>
        </ul>
	</div>
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Infos']['ResetTable']['Title']}</span></div>
        {template="include_resetTable"}
	</div>
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Infos']['MResetTable']['Title']}</span></div>
        {template="include_masterResetTable"}
    </div>
HTML;
/********** End: serverInfos **********/

/********** Begin: serverTeam **********/
$CTM_TEMPLATE_DATABASE['serverTeam'] = <<<HTML
	<div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Team']['Title']}</span></div>
        <p>
        	{::x####$####x::this->lang->words['Team']['Text']}
        </p>
	</div>
    <div class="box-content">
        <if syntax="count(::x####$####x::team_members) > 0">
        <script type="text/javascript">
		::x####$####x::(function()
		{
			<foreach loop="::x####$####x::team_members as ::x####$####x::key => ::x####$####x::value">
			::x####$####x::("#showServer_{::x####$####x::key}").tooltip("{::x####$####x::this->lang->words['Team']['Members']['Server']} <strong>{::x####$####x::value['server']}</strong>", { hook: false, width: 200 });
			</foreach>
		});
		</script>
        <foreach loop="::x####$####x::team_members as ::x####$####x::key => ::x####$####x::value">
        <div class="setQuote">
        	<table width="100%" border="0" cellpadding="7" class="tableBackLine">
            	<tr>
                	<td width="20%" align="center">
                    	<img src="{::x####$####x::value['image']}" width="120" height="120" style="border: 1px solid #B3B3B3;" class="image" />
                        <br />{::x####$####x::value['format_prefix']}{::x####$####x::value['title']}{::x####$####x::value['format_suffix']}
					</td>
                    <td>
                    	<table width="100%" border="0" align="center" cellpadding="7" style="text-align:center;" class="tableBackColumn">
                        	<tr>
                            	<td width="44%">{::x####$####x::this->lang->words['Team']['Members']['Name']}</td>
                                <td width="56%">{::x####$####x::value['format_prefix']}{::x####$####x::value['name']}{::x####$####x::value['format_suffix']}</td>
                            </tr>
                            <tr>
                            	<td>{::x####$####x::this->lang->words['Team']['Members']['Group']}</td>
                                <td>{::x####$####x::value['group']}</td>
                            </tr>
                            <tr>
                            	<td>{::x####$####x::this->lang->words['Team']['Members']['Contact']}</td>
                                <td>{::x####$####x::value['contact']}</td>
                            </tr>
                            <tr>
                            	<td>{::x####$####x::this->lang->words['Team']['Members']['Class']}</td>
                                <td>{::x####$####x::value['class']}</td>
                            </tr>
                            <tr>
                            	<td>{::x####$####x::this->lang->words['Team']['Members']['Status']}</td>
                                <td id="showServer_{::x####$####x::key}">{::x####$####x::value['status']}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
    		</table>
    	</div>
        </foreach>
        <else />
        <div class="info-box">{::x####$####x::this->lang->words['Team']['Message']}</div>
        </if>
    </div>
HTML;
/********** End: serverTeam **********/

/********** Begin: serverTerms **********/
$CTM_TEMPLATE_DATABASE['serverTerms'] = <<<HTML
	<div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Terms']['Title']}</span></div>
        <if syntax="::x####$####x::load_terms">
		<div class="blockquote">
            {::x####$####x::load_terms}
		</div>
        <else />
        <div class="error-box">{::x####$####x::this->lang->words['Terms']['Message']}</div>
        </if>
    </div>
HTML;
/********** End: serverTerms **********/