<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_rankings                                  */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: rankingPage **********/
$CTM_TEMPLATE_DATABASE['rankingPage'] = <<<HTML
	<script type="text/javascript">
    ::x####$####x::(function()
    {
        ::x####$####x::("#btn-search").click(function()
        {
            if(::x####$####x::("#Ranking option:selected").val().length < 1)
                CTM.Message("{::x####$####x::this->lang->words['Rankings']['Generator']['Messages']['SelectRank']}", 1, "rankingResult");
            else if(::x####$####x::("#Limit option:selected").val().length < 1)
                CTM.Message("{::x####$####x::this->lang->words['Rankings']['Generator']['Messages']['SelectLimit']}", 1, "rankingResult");
            else
                CTM.AjaxLoad("?app=core&module=rankings&gerate=true", "rankingResult", "frm-rank");
        });
    });
    </script>
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['Title']}</span></div>
        <form name="frm-rank" id="frm-rank">
        	<label>{::x####$####x::this->lang->words['Rankings']['Generator']['Rank']} </label>
            <select name="Ranking" id="Ranking">
            	<option value="" disabled="disabled" selected="selected"> -- {::x####$####x::this->lang->words['Words']['Select']}</option>
                <if syntax="::x####$####x::ranking_generator['one_ResetCount_enabled'] == true">
                <optgroup label=" -- {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Resets']['Category']}">
                	<if syntax="::x####$####x::this->settings['RANKING']['RESETS_GENERAL'][0] == true">
            		<option value="resetsGeneral"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Resets']['General']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['RESETS_DAILY'][0] == true">
                    <option value="resetsDaily"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Resets']['Daily']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['RESETS_WEEKLY'][0] == true">
                    <option value="resetsWeekly"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Resets']['Weekly']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['RESETS_MONTHLY'][0] == true">
                    <option value="resetsMonthly"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Resets']['Monthly']}</option>
                    </if>
                </optgroup>
                </if>
                <if syntax="::x####$####x::ranking_generator['one_MResetCount_enabled'] == true">
                <optgroup label=" -- {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['MResets']['Category']}">
                	<if syntax="::x####$####x::this->settings['RANKING']['MASTER_RESETS'][0] == true">
            		<option value="masterResets"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['MResets']['General']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['MRESETS_DAILY'][0] == true">
                    <option value="mresetsDaily"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['MResets']['Daily']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['MRESETS_WEEKLY'][0] == true">
                    <option value="mresetsWeekly"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['MResets']['Weekly']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['MRESETS_MONTHLY'][0] == true">
                    <option value="mresetsMonthly"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['MResets']['Monthly']}</option>
                    </if>
                </optgroup>
                </if>
                <if syntax="::x####$####x::ranking_generator['one_KillCount_enabled'] == true">
                <optgroup label=" -- {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Kills']['Category']}">
                	<if syntax="::x####$####x::this->settings['RANKING']['PK_KILLS'][0] == true">
                    <option value="pkKills"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Kills']['PkKills']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['HERO_KILLS'][0] == true">
                    <option value="heroKills"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Kills']['HeroKills']}</option>
                    </if>
                </optgroup>
                </if>
                <if syntax="::x####$####x::ranking_generator['one_Others_enabled'] == true">
                <optgroup label=" -- {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Others']['Category']}">
                	<if syntax="::x####$####x::this->settings['RANKING']['LEVEL'][0] == true">
                	<option value="level"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Others']['Level']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['MASTER_LEVEL'][0] == true">
                	<option value="masterLevel"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Others']['MLevel']}</option>
                    </if>
                    <if syntax="::x####$####x::this->settings['RANKING']['GUILDS'][0] == true">
                	<option value="guilds"> - {::x####$####x::this->lang->words['Rankings']['Generator']['Select']['Others']['Guilds']}</option>
                    </if>
                </optgroup>
                </if>
			</select>
            <label>&nbsp;&nbsp;{::x####$####x::this->lang->words['Rankings']['Generator']['Limit']} </label>
            <select name="Limit" id="Limit">
            	<foreach loop="::x####$####x::this->settings['RANKING']['GENERATOR']['LIMIT'] as ::x####$####x::limit">
                <option value="{::x####$####x::limit}">{::x####$####x::limit} {::x####$####x::this->lang->words['Rankings']['Generator']['Results']}</option>
            	</foreach>
            </select>
            <input type="button" name="btn-search" id="btn-search" value="{::x####$####x::this->lang->words['Rankings']['Generator']['Button']}">
		</form>
        <if syntax="::x####$####x::this->settings['WEBCACHE']['RANKINGS']['SWITCH'] == true">
        <div class="right"><strong><i>{::x####$####x::this->lang->words['Rankings']['Generator']['Cache']}</i></strong></div>
        </if>
	</div>
    <div id="rankingResult">
    <if syntax="::x####$####x::ranking_generator['auto_load_ranking']">
    <script type="text/javascript">
	::x####$####x::(document).ready(function(e)
	{
		if(e)
			CTM.AjaxLoad("?app=core&module=rankings&load={::x####$####x::ranking_generator['auto_load_ranking']}", '*rankingResult');
	});
    </script>
	</if>
    </div>
HTML;
/********** End: rankingPage **********/

/********** Begin: ranking_guilds **********/
$CTM_TEMPLATE_DATABASE['ranking_guilds'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['Guilds']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['Score']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['G_Master']} </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_guilds **********/

/********** Begin: ranking_heroKills **********/
$CTM_TEMPLATE_DATABASE['ranking_heroKills'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['HeroKills']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['Kills']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_heroKills **********/

/********** Begin: ranking_level **********/
$CTM_TEMPLATE_DATABASE['ranking_level'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['Level']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['Level']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_level **********/

/********** Begin: ranking_masterLevel **********/
$CTM_TEMPLATE_DATABASE['ranking_masterLevel'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['MasterLevel']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['MLevel']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_masterLevel **********/

/********** Begin: ranking_masterResets **********/
$CTM_TEMPLATE_DATABASE['ranking_masterResets'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['MasterResets']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['MResets']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_masterResets **********/

/********** Begin: ranking_mresetsDaily **********/
$CTM_TEMPLATE_DATABASE['ranking_mresetsDaily'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['MResetsDaily']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['MRDaily']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_mresetsDaily **********/

/********** Begin: ranking_mresetsMonthly **********/
$CTM_TEMPLATE_DATABASE['ranking_mresetsMonthly'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['MResetsMonthly']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['MRMonthly']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_mresetsMonthly **********/

/********** Begin: ranking_mresetsWeekly **********/
$CTM_TEMPLATE_DATABASE['ranking_mresetsWeekly'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['MResetsWeekly']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['MRWeekly']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_mresetsWeekly **********/

/********** Begin: ranking_pkKills **********/
$CTM_TEMPLATE_DATABASE['ranking_pkKills'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['PkKills']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['Kills']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_pkKills **********/

/********** Begin: ranking_resetsDaily **********/
$CTM_TEMPLATE_DATABASE['ranking_resetsDaily'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['ResetsDaily']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['RDaily']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_resetsDaily **********/

/********** Begin: ranking_resetsGeneral **********/
$CTM_TEMPLATE_DATABASE['ranking_resetsGeneral'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['ResetsGeneral']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['Resets']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_resetsGeneral **********/

/********** Begin: ranking_resetsMonthly **********/
$CTM_TEMPLATE_DATABASE['ranking_resetsMonthly'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['ResetsMonthly']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['RMonthly']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_resetsMonthly **********/

/********** Begin: ranking_resetsWeekly **********/
$CTM_TEMPLATE_DATABASE['ranking_resetsWeekly'] = <<<HTML
<div class="box-content">
	<div class="header"><span>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Titles']['ResetsWeekly']}</span></div>
    <if syntax="count(::x####$####x::ranking_result) > 0">
    <script type="text/javascript">
	::x####$####x::(document).ready(function()
	{
		::x####$####x::(".CharLink").click(function()
		{
			var charName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/char/'+charName,'content');
		});
		::x####$####x::(".GuildLink").click(function()
		{
			var guildName = encodeURIComponent(::x####$####x::(this).attr("rel"));
			CTM.Load('?/guild/'+guildName,'content');
		});
	});
	</script>
    <ul class="rank">
    	<foreach loop="::x####$####x::ranking_result as ::x####$####x::rank => ::x####$####x::infos">
    	<li>
        	<img src="{::x####$####x::infos['image']}" width="50" height="50">
            <p><strong>{::x####$####x::rank}º - </strong><a href="javascript: void(0);" class="CharLink" rel="{::x####$####x::infos['name']}">{::x####$####x::infos['name']}</a></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Results']['RWeekly']} </strong><span class="blue">{::x####$####x::infos['result']}</span></p>
            <p><strong>{::x####$####x::this->lang->words['Rankings']['LoadRank']['Guild']} </strong><a href="javascript: void(0);" class="GuildLink" rel="{::x####$####x::infos['secondary']}">{::x####$####x::infos['secondary']}</a></p>
    	</li>   
        </foreach>     
	</ul>
    <else />
    <div class="error-box">{::x####$####x::this->lang->words['Rankings']['LoadRank']['Messages']['NotResult']}</div>
    </if>
</div>
HTML;
/********** End: ranking_resetsWeekly **********/