<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Template: Harmony                                       */
/* DB file: skin_coinvip                                   */
/* DB generated in 20/10/2013 - 04:34h                     */
/***********************************************************/
/* This is a cache file generated by                       */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: bankdata **********/
$CTM_TEMPLATE_DATABASE['bankdata'] = <<<HTML
	<div class="box-content">
		<div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['BankData']['Title']}</span></div>
		<p> 
			<strong>{::x####$####x::this->lang->words['CoinVIP']['BankData']['Info'][1]}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['BankData']['Info'][2]}<br /><br />
			<strong>{::x####$####x::this->lang->words['CoinVIP']['BankData']['Info'][3]}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['BankData']['Info'][4]}<br /><br />
		</p>
        <if syntax="count(::x####$####x::this->settings['PAYMENTMETHOD']['BANK']) > 0">
        <foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'] as ::x####$####x::_key => ::x####$####x::trash">
		<div class="blockquote">
			<foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'][::x####$####x::_key] as ::x####$####x::k => ::x####$####x::_trash">
            <foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'][::x####$####x::_key][::x####$####x::k] as ::x####$####x::key => ::x####$####x::value">
			&raquo; <strong>{::x####$####x::key}</strong> {::x####$####x::value}<br />
            </foreach>
			</foreach>
		</div>
		</foreach>
        </if>
	</div>
HTML;
/********** End: bankdata **********/

/********** Begin: coinvip **********/
$CTM_TEMPLATE_DATABASE['coinvip'] = <<<HTML
	<if syntax="::x####$####x::coinvip['auto_load_page']">
	<script type="text/javascript">
	::x####$####x::(document).ready(function(e)
	{
		if(e)
			CTM.AjaxLoad("?app=core&module=coinvip&load={::x####$####x::coinvip['auto_load_page']}", ".showOption");
    });
    </script>
	</if>
    
	<div class="box-content">
		<div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['Title']}</span></div>
		<ul class="info">
			<li><a href="javascript: void(0);" onclick="CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=advantages','.showOption');">&raquo; {::x####$####x::this->lang->words['CoinVIP']['Menu']['VIP_Advantages']}</a></li>
			<li><a href="javascript: void(0);" onclick="CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=howtobuy','.showOption');">&raquo; {::x####$####x::this->lang->words['CoinVIP']['Menu']['HowToBuy']}</a></li>
			<li><a href="javascript: void(0);" onclick="CTM.Load('?app=core&amp;module=userpanel&amp;option=buyVIP','.content');">&raquo; {::x####$####x::this->lang->words['CoinVIP']['Menu']['BuyVIP']}</a></li>
			<li><a href="javascript: void(0);" onclick="CTM.AjaxLoad('?app=core&amp;module=coinvip&amp;load=bankdata','.showOption');">&raquo; {::x####$####x::this->lang->words['CoinVIP']['Menu']['BankData']}</a></li>
		</ul>
	</div>
	<div id="showOption"></div>
HTML;
/********** End: coinvip **********/

/********** Begin: howtobuy **********/
$CTM_TEMPLATE_DATABASE['howtobuy'] = <<<HTML
	<div class="box-content">
		<div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Title']}</span></div>
		<p>
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['What']}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['What_R']}<br /><br />
            
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Obtain']}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Obtain_R']}<br /><br />
            
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Buy']}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Buy_R']}<br /><br />
            
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Bank'][1]}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Bank'][2]}<br /><br />
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Bank'][3]}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Bank'][4]}<br /><br />
		</p>
		<if syntax="count(::x####$####x::this->settings['PAYMENTMETHOD']['BANK']) > 0">
        <foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'] as ::x####$####x::_key => ::x####$####x::trash">
		<div class="blockquote">
			<foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'][::x####$####x::_key] as ::x####$####x::k => ::x####$####x::_trash">
            <foreach loop="::x####$####x::this->settings['PAYMENTMETHOD']['BANK'][::x####$####x::_key][::x####$####x::k] as ::x####$####x::key => ::x####$####x::value">
			&raquo; <strong>{::x####$####x::key}</strong> {::x####$####x::value}<br />
            </foreach>
			</foreach>
		</div>
		</foreach>
        </if>
            
		<p>
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Confirm']}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Confirm_R']}<br /><br />
			<strong>{::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Time']}</strong><br />
			&raquo; {::x####$####x::this->lang->words['CoinVIP']['HowToBuy']['Time_R']}<br /><br />
		</p>
	</div>
HTML;
/********** End: howtobuy **********/

/********** Begin: include_masterResetTable **********/
$CTM_TEMPLATE_DATABASE['include_masterResetTable'] = <<<HTML
<table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
            <thead>
                <tr width="100%">
                    <th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
                </tr>
            </thead>
            <tbody>
            	<if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] < 3">
            	<tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetsRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_require'][5]}</td>
                    </if>
                </tr>
                </if>
            	<tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['StrengthRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['strength_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['DexterityRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['dexterity_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['VitalityRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['vitality_require']}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['EnergyRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['energy_require']}</td>
                    </if>
                </tr>
                <if syntax="MUSERVER_VERSION >= 1">
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['CommandRequire']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['command_require']}</td>
                    </if>
                </tr>
                </if>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['money_require'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['MASTER_RESET'][0xFF]['MODE'] == 1">
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetsRemove']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['resets_remove'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ResetPoints']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['reset_points'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['clear_quest'][5]}</td>
                    </if>
                </tr>
                <tr>
                    <td style="color:#FF0000">{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['CoinAward']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['masterResetTable']['coin_award'][5]}</td>
                    </if>
                </tr>
            </tbody>
        </table>
HTML;
/********** End: include_masterResetTable **********/

/********** Begin: include_resetTable **********/
$CTM_TEMPLATE_DATABASE['include_resetTable'] = <<<HTML
<if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] < 4">
        <table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
        	<thead>
            	<tr width="100%">
                	<th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['money_require'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelAfter']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['level_after'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0">
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['SetPoints']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['set_points'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][0]}</td>
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::coinvip['vip_advantages']['resetTable']['clear_quest'][5]}</td>
                    </if>
                </tr>
			</tbody>
		</table>
        <else />
        <foreach loop="::x####$####x::coinvip['vip_advantages']['resetTable'] as ::x####$####x::key => ::x####$####x::table">
        <h4>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['Table']} {::x####$####x::key}</h4>
        <table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
        	<thead>
            	<tr width="100%">
                	<th>#</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
				</tr>
			</thead>
            <tbody>
            	<tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelReset']}</td>
                    <td>{::x####$####x::table['level_reset'][0]}</td>
                    <td>{::x####$####x::table['level_reset'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['level_reset'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['level_reset'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['level_reset'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['level_reset'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['MoneyReset']}</td>
                    <td>{::x####$####x::table['money_require'][0]}</td>
                    <td>{::x####$####x::table['money_require'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['money_require'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['money_require'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['money_require'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['money_require'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['LevelAfter']}</td>
                    <td>{::x####$####x::table['level_after'][0]}</td>
                    <td>{::x####$####x::table['level_after'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['level_after'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['level_after'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['level_after'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['level_after'][5]}</td>
                    </if>
                </tr>
                <if syntax="::x####$####x::this->settings['USERPANEL']['CHARACTER']['RESET_SYSTEM'][0xFF]['MODE'] > 0">
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['SetPoints']}</td>
                    <td>{::x####$####x::table['set_points'][0]}</td>
                    <td>{::x####$####x::table['set_points'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['set_points'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['set_points'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['set_points'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['set_points'][5]}</td>
                    </if>
                </tr>
                </if>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearInvent']}</td>
                    <td>{::x####$####x::table['clear_invent'][0]}</td>
                    <td>{::x####$####x::table['clear_invent'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_invent'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_invent'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_invent'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_invent'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearSkill']}</td>
                    <td>{::x####$####x::table['clear_skill'][0]}</td>
                    <td>{::x####$####x::table['clear_skill'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_skill'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_skill'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_skill'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_skill'][5]}</td>
                    </if>
                </tr>
                <tr>
                	<td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['ClearQuest']}</td>
                    <td>{::x####$####x::table['clear_quest'][0]}</td>
                    <td>{::x####$####x::table['clear_quest'][1]}</td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td>{::x####$####x::table['clear_quest'][2]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td>{::x####$####x::table['clear_quest'][3]}</td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td>{::x####$####x::table['clear_quest'][4]}</td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td>{::x####$####x::table['clear_quest'][5]}</td>
                    </if>
                </tr>
			</tbody>
		</table>
        </foreach>
        </if>
HTML;
/********** End: include_resetTable **********/

/********** Begin: vip_advantages **********/
$CTM_TEMPLATE_DATABASE['vip_advantages'] = <<<HTML
    <div class="box-content">
    	<div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Title']}</span></div>
    	<p>
        	{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Text']}
		</p>
    </div>
    <div class="box-content">
        <div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Title']}</span></div>
        <table width="100%" border="0" align="center" cellpadding="7" class="tableBackColumn" style="text-align:center;">
            <thead>
                <tr width="100%">
                    <th>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Service']}</th>
                    <th>{::x####$####x::this->lang->words['Words']['Free']}</th>
                    <th>{const="VIP_NAME_1"}</th>
                    <if syntax="VIP_NUMBER >= 2">
                    <th>{const="VIP_NAME_2"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <th>{const="VIP_NAME_3"}</th>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <th>{const="VIP_NAME_4"}</th>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <th>{const="VIP_NAME_5"}</th>
                    </if>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeData']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_DATA'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeMail']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_MAIL'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangePID']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_PID'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['VirtualVault']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['VIRTUAL_VAULT'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['DisconnectGame']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISCONNECT_GAME'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ResetSystem']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['RESET_SYSTEM'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['MasterReset']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MASTER_RESET'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['TransferResets']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['TRANSFER_RESETS'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ClearPk']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CLEAR_PK'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeClass']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_CLASS'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeName']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_NAME'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['MoveCharacter']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MOVE_CHARACTER'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ManageProfile']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['MANAGE_PROFILE'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['ChangeAvatar']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['CHANGE_AVATAR'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['RepairPoints']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REPAIR_POINTS'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['RedistributePoints']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['REDISTRIBUTE_POINTS'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
                <tr>
                    <td>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['Services']['DistributePoints']}</td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][0]}.png" style="border: none;" /></td>
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][1]}.png" style="border: none;" /></td>
                    <if syntax="VIP_NUMBER >= 2">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][2]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 3">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][3]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER >= 4">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][4]}.png" style="border: none;" /></td>
                    </if>
                    <if syntax="VIP_NUMBER == 5">
                    <td><img src="{::x####$####x::this->vars['style_dirs']['images']}icons/{::x####$####x::coinvip['vip_advantages']['advantages']['DISTRIBUTE_POINTS'][5]}.png" style="border: none;" /></td>
                    </if>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="box-content">
        <div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['ResetTable']['Title']}</span></div>
        {template="include_resetTable"}
    </div>
    <div class="box-content">
        <div class="header"><span>{::x####$####x::this->lang->words['CoinVIP']['VIP_Advantages']['Advantages']['MResetTable']['Title']}</span></div>
        {template="include_masterResetTable"}
    </div>
HTML;
/********** End: vip_advantages **********/