<?php
/***********************************************************/
/* Cetemaster Services, Limited                            */
/* Copyright (c) 2010-2013. All Rights Reserved,           */
/* www.cetemaster.com.br / www.cetemaster.com              */
/***********************************************************/
/* File generated by Cetemaster PHP Template Engine        */
/* Skin sources - skin_sources.php                         */
/* DB generated in 26/08/2013 - 02:50h                     */
/***********************************************************/
/* This is a cache file generated by Effect Web 2.0.0      */
/* DO NOT EDIT DIRECTLY                                    */
/* The changes are not saved to the cache automatically    */
/***********************************************************/

/********** Begin: Harmony **********/
$CTM_SKIN_SOURCES['Harmony'] = array
(
	"Name" => "Effect Web Harmony",
	"CodeKey" => "XhXUBQdQKLlwXW4j+3c4QMM0CNA=",
	"Author" => array
	(
		"Name" => "LucasHP: Cetemaster Services",
		"Site" => "www.cetemaster.com.br",
	),
);
/********** End: Harmony **********/